### ISSUE TITLE
feat: Imeplement langchain vector stores interface

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#11]
https://python.langchain.com/en/latest/reference/modules/vectorstores.html?highlight=vector

**Comment by gaocegege** [comment]
We should implement a new vector store in langchain `postgres`

**Comment by gaocegege** [comment]
Thanks, I assigned this to you.

**Comment by BeautyyuYanli** [comment]
Completed by https://github.com/langchain-ai/langchain/pull/12718

Doc on https://python.langchain.com/docs/integrations/vectorstores/pgvecto_rs

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:
