### ISSUE TITLE
feat: PCA+Percentile for k-means initial centroid

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/pgvecto.rs#114]
It seems that PCA+Percentile method is better than kmeans++ based on this thesis.

ref: https://link.springer.com/article/10.1007/s40745-022-00428-2
More dicussion, reasearch and benchmark may need before carry out.

![image](https://github.com/tensorchord/pgvecto.rs/assets/19801166/ad8c9f60-2127-4472-95dd-ccd2d69c3db1)

**Comment by VoVAllen** [comment]
PCA changes the original data and highly depends on the original data distribution. Faiss and some quantization method (Optimized product quantization (OPQ)) has this kind of method, but hard to make it as default option since you cannot assume user's vector distribution

**Comment by cutecutecat** [comment]
> PCA changes the original data and highly depends on the original data distribution. Faiss and some quantization method (Optimized product quantization (OPQ)) has this kind of method, but hard to make it as default option since you cannot assume user's vector distribution

Yes, sorry about that I forgot original data is really important for DB area.
