### ISSUE TITLE
UPDATE SQL question

### ISSUE THREAD

**Issue by csycsycsy007** [tensorchord/pgvecto.rs#119]
when run:
    update items set "embedding"='[0,0,0]' where id = 1;
    
result:
   ERROR:  called `Result::unwrap()` on an `Err` value: Closed
   
Is my SQL statement incorrect?

**Comment by usamoi** [comment]
Can you give more information? Did you follow `docs/install.md` and modify `postgresql.conf`?

**Comment by cutecutecat** [comment]
I have tested this query at my example DB and it works fine.
![image](https://github.com/tensorchord/pgvecto.rs/assets/19801166/9b977ac5-a8ef-47b7-ab10-3938898acd80)


Could you please provide steps to reproduce this error?

**Comment by VoVAllen** [comment]
Closed for now. If you still meet this problem, please feel free to reopen it.
