### ISSUE TITLE
feat: Release Docker images for other major versions of Postgres

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#129]
It would make adoption easier if images were available for more environments in the wild. Our use-case is a self-hosted photo library where we're considering switching to pgvecto.rs. Since we currently use Postgres 14, it would be convenient if we could switch without maintaining our own Postgres images for amd64 and arm64.

**Comment by mertalev** [comment]
Thank you so much for working on this!

**Comment by VoVAllen** [comment]
I'm fixing the arm release. Please feel free to try our latest version, the insert performance is 10x faster than the previous version (and probably 100x faster than pgvector), and the query performance also boosts 2x-3x based on our preliminary tests.

**Comment by mertalev** [comment]
I'll be doing more testing soon, so I'll keep you posted!

I also love how active and helpful the pgvecto.rs team has been. I'd like to thank you again on behalf of the Immich team for addressing any concerns we had, and for developing this great project.
