### ISSUE TITLE
chore: Remove nightly release in Github Release

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#142]

**Comment by cutecutecat** [comment]
It seems to merge `release` and `prerelease` and the changelog base is fetched from last release.

I think we could use a changlog writer which can accept parameter `ignorePreReleases` like:
https://github.com/mikepenz/release-changelog-builder-action

**Comment by gaocegege** [comment]
I think we could put it in a higher priority. The changelog is not human readable.

**Comment by VoVAllen** [comment]
The process should be changed. Release should be triggered by github ui release, instead of github action
