### ISSUE TITLE
bug: error on inserting new values with hnsw index after restart

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#146]
## Description

Creating a new HNSW index and inserting into the relevant table works as expected, but after restarting the Docker container, any attempt to insert returns the error ```[XX000] ERROR: called `Result::unwrap()` on an `Err` value: Closed```. Dropping the index is the only way I've found to insert successfully.

## Steps to reproduce

1. Create a container from the `pg14-v0.1.8-amd64` tagged image
2. Run the following commands:

```
CREATE TABLE insert_err_test (
"assetId"  uuid PRIMARY KEY,
embedding  vector(512) NOT NULL );

CREATE INDEX insert_err_index ON insert_err_test
USING vectors (embedding dot_ops) WITH (options = $$
[indexing.hnsw]
m = 16
ef_construction = 300
$$);

INSERT INTO insert_err_test ("assetId", embedding)
SELECT gen_random_uuid(), array_agg(random()::real)
FROM generate_series(1, 512);
```
3. Restart the Postgres container
4. Attempt to run the below command
```
INSERT INTO insert_err_test ("assetId", embedding)
SELECT gen_random_uuid(), array_agg(random()::real)
FROM generate_series(1, 512);
```
5. Observe a wait of 15s followed by the error ```[XX000] ERROR: called `Result::unwrap()` on an `Err` value: Closed```

**Comment by VoVAllen** [comment]
Thanks for your report! I think my previous comment is a bit misleading. Now the index building process is asynchronous. It will search in a brute-force way until the index is ready. So the bug happens before the index is actually ready I think. We'll fix this!

**Comment by mertalev** [comment]
Thank you for the quick fix!
