### ISSUE TITLE
Question: Why (or what for) is pgvecto.rs planning to implement Logical Replication?

### ISSUE THREAD

**Issue by MMeent** [tensorchord/pgvecto.rs#147]
> The drawback is that implementing logical replication in PostgreSQL requires additional effort. We have plans to implement it in the future.
> 
> [Doc link](https://github.com/tensorchord/pgvecto.rs/blob/main/docs/comparison-pgvector.md#index-build-and-persistence-and-wal-amplification)

Why does this index method need to implement logical replication?

Isn't logical replication exclusively limited to authorative data stores, i.e. tables, and not meant for the WAL of index methods (because of duplicate command decoding, etc.)?

**Comment by VoVAllen** [comment]
Because the index is not stored in postgre's internal storage system, we managed it separately due to scalability issues. Thus the index may not be replicated through the logical replication properly. The standby instance may not have the correct index for that. However, we believe this can be fixed, but currently we lack the bandwidth. Hopefully, we can get this done in January.

**Comment by VoVAllen** [comment]
@MMeent Thanks for your clarification. We haven't tried logical replication yet and have some misconceptions about it. If it's "INSERT/UPDATE/DELETE statement shipping for some tables", we definitely support that. The vector data is stored in pg's storage. Only index is stored seperately.

**Comment by VoVAllen** [comment]
@MMeent Thanks for your clarification. We haven't tried logical replication yet and have some misconceptions about it. If it's "INSERT/UPDATE/DELETE statement shipping for some tables", we definitely support that. The vector data is stored in pg's storage. Only index is stored seperately.

**Comment by l0nax** [comment]
Is my understanding correct that a _Custom WAL Resource Manager_ must be implemented to support stream replication fully?

**Comment by VoVAllen** [comment]
We have tested pgvecto.rs with logical replication and it worked as expected. For streaming replication, we need more investigations. Tracked in #251
