### ISSUE TITLE
bug: empty nightly release

### ISSUE THREAD

**Issue by usamoi** [tensorchord/pgvecto.rs#168]
https://github.com/tensorchord/pgvecto.rs/actions/runs/6990060374/job/19019198142
https://github.com/tensorchord/pgvecto.rs/blob/main/.github/workflows/release.yml#L95
https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.0.0-nightly.20231126

**Comment by gaocegege** [comment]
cc @VoVAllen

**Comment by VoVAllen** [comment]
We don't have modification on 11/26, so no release is expected. We only need to fix the release tag.

**Comment by VoVAllen** [comment]
https://github.com/tensorchord/pgvecto.rs/actions/runs/6990060374/job/19019198142#step:4:21
