### ISSUE TITLE
feat: Support indexing algorithms

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#17]
Ref https://github.com/tensorchord/pgvecto.rs/pull/16

We are implementing the first naive index algorithm. But we still need ivf, hnsw and many other algos.

- [x] #19 
- [ ] #18 
- [ ] #20

**Comment by VoVAllen** [comment]
Disk oriented index might be more suitable for postgres, such as 
- https://github.com/microsoft/DiskANN
- https://github.com/microsoft/SPTAG

**Comment by gaocegege** [comment]
SGTM. I do not think memory-based index is necessary for most cases.
