### ISSUE TITLE
Can we support diskann for now?

### ISSUE THREAD

**Issue by JackTan25** [tensorchord/pgvecto.rs#173]

**Comment by VoVAllen** [comment]
We do have plan to support diskann, but currently lack of bandwidth.

**Comment by VoVAllen** [comment]
What's your scenarios and how many vectors do you have now?

**Comment by gaocegege** [comment]
I am closing this

https://github.com/tensorchord/pgvecto.rs/issues/24 will keep track of the DiskANN.
