### ISSUE TITLE
v0.1.11 and main branch: error: `MaybeUninit::<T>::zeroed` is not yet stable as a const fn

### ISSUE THREAD

**Issue by Weuxel** [tensorchord/pgvecto.rs#179]
Following the docs, compiling from source i can not get past this error.

```
Compiling vectors v0.1.1 (/opt/pgvecto.rs)
error: `MaybeUninit::<T>::zeroed` is not yet stable as a const fn
  --> src/postgres/index.rs:46:18
   |
46 |         unsafe { std::mem::MaybeUninit::<pgrx::pg_sys::IndexAmRoutine>::zeroed().assume_init() };
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_maybe_uninit_zeroed)]` to the crate attributes to enable

error: could not compile `vectors` (lib) due to previous error
```
The docs are not very detailed on the prerequisites of rust. After some previous errors, i activated nightly and miri and updated from my distros default rust version 1.71.1 to 1.74.1.

Is this a bug, something that is missing in the docs, or am i doing something wrong?

Thanks,
Norman

**Comment by usamoi** [comment]
You should install `rustup`, instead of `rustc`. If you are using `rustup` to manage toolchains, the nightly `rustc` of proper version will be download automatically since there is a `rust-toolchain.toml` file. It's the recommanded way to develop and build from source.
