### ISSUE TITLE
feat: Show index size in index info table

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#185]

**Comment by usamoi** [comment]
We can extend `IndexStat` to implement it. We give details including size of every segment. For sealed segment, we can just sum up the size of all files. For growing segment, we calculate the size of all vectors.

**Comment by kemingy** [comment]
> We can extend `IndexStat` to implement it. We give details including size of every segment. For sealed segment, we can just sum up the size of all files. For growing segment, we calculate the size of all vectors.

Which file should be count for the sealed segments?

**Comment by usamoi** [comment]
> Which file should be count for the sealed segments?

All files in the folder belong to the sealed segments.
