### ISSUE TITLE
Error when upgrading from 0.1.11 to 0.1.12

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#191]
Hi, I tried changing from `tensorchord/pgvecto-rs:pg14-v0.1.11` to `tensorchord/pgvecto-rs:pg14-v0.1.12` and got this error:

```
[2023-12-17T22:19:28Z ERROR vectors::bgworker] Panickied. Info: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: Error("unknown variant `Cosine`, expected one of `L2`, `Cos`, `Dot`", line: 1, column: 67)), location: Location { file: "crates/service/src/utils/file_atomic.rs", line: 51, col: 52 }, can_unwind: true, force_no_backtrace: false }. Backtrace: disabled backtrace.
```
It seems to be because of the change from `cosine_ops` to `vector_cos_ops`. Dropping the index does not work either. I understand that the extension is still in beta, but I would hope that changes wouldn't affect existing tables or indices when upgrading. Is it possible for you to make this backwards compatible?

Edit: I also get this error
```
ERROR:  could not find function "vector_typmod_out_wrapper" in file "/usr/lib/postgresql/14/lib/vectors.so"
```

**Comment by mileszim** [comment]
same here, this totally effed my db of like 10 million vectors. not currently able to upgrade and a breaking change like this is unacceptable, so switching to timescaledb for now

**Comment by VoVAllen** [comment]
@mileszim @mertalev Really sorry for the problem. Unfortunately some breaking change is needed now to support new features. We plan to release a long-term stable version in January which will guarantee the backward compatibility. However, it's not reasonable to have panic error for users. We will make a immediate patch to ensure user can REINEX/DROP index when breaking change as a temporary workaround.

**Comment by VoVAllen** [comment]
Does REINDEX sound a valid solution now?

**Comment by mertalev** [comment]
Yeah, that would be fine. Would that also fix the `vector_typmod_out_wrapper` error, or is that separate?

**Comment by VoVAllen** [comment]
Yes. We plan to fix `vector_typmod_out_wrapper` error together

**Comment by mertalev** [comment]
Perfect! We were planning on upgrading pgvecto.rs in a few weeks, so in that case I think we can keep it at 0.11.1 for now and upgrade to the stable release next month.

**Comment by JoePassanante** [comment]
+1 I ended up dumping my database, upgrading pgvect, and restoring.
