### ISSUE TITLE
error: linker `x86_64-linux-gnu-gcc` not found

### ISSUE THREAD

**Issue by dnlldl** [tensorchord/pgvecto.rs#193]
Trying VERY hard to make this work on OpenSUSE 15.4 using these instructions:
https://github.com/tensorchord/pgvecto.rs/blob/main/docs/installation.md#install-from-source

Everything works perfectly fine until I do the `cargo pgrx install --sudo --release`. Here is the output:
```
postgres@vm-dev:/tmp/pgvecto.rs> cargo pgrx install -c /usr/lib/postgresql14/bin/pg_config --release
       Using PgConfig("pg14") and `pg_config` from /usr/lib/postgresql14/bin/pg_config
    Building extension with features pg14
     Running command "/var/lib/pgsql/.rustup/toolchains/nightly-2023-11-15-x86_64-unknown-linux-gnu/bin/cargo" "build" "--release" "--features" "pg14" "--no-default-features" "--message-format=json-render-diagnostics"
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.151
error: linker `x86_64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `proc-macro2` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc` (build script) due to previous error
```
I did try as `root` as well, exact same error. I noticed the following:
```
vm-dev:/tmp/pgvecto.rs # which gcc
/usr/bin/gcc
vm-dev:/tmp/pgvecto.rs # gcc --version
gcc (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

vm-dev:/tmp/pgvecto.rs # ls -l /usr/bin/x86_64*
lrwxrwxrwx 1 root root      7 May 17  2023 /usr/bin/x86_64 -> setarch
-rwxr-xr-x 2 root root 574144 May 25  2018 /usr/bin/x86_64-suse-linux-gnu-pkg-config
```
Not sure what to try from there.

**Comment by VoVAllen** [comment]
Can you try delete https://github.com/tensorchord/pgvecto.rs/blob/9e46faa91d3c295578b570a5e93e15ff8ae10010/.cargo/config.toml#L8-L9 ?

Ref: https://github.com/tensorchord/pgvecto.rs/issues/190#issuecomment-1859222473

**Comment by dnlldl** [comment]
> Can you try delete this part?
> 
> https://github.com/tensorchord/pgvecto.rs/blob/9e46faa91d3c295578b570a5e93e15ff8ae10010/.cargo/config.toml#L8-L9
> 
> Ref: [#190 (comment)](https://github.com/tensorchord/pgvecto.rs/issues/190#issuecomment-1859222473)

and... fixed! thank you.

**Comment by VoVAllen** [comment]
More details can be found in #190 . The configuration is currently set for release and cross-compilation purposes, which helps rust to find the correct linker when compiling arm binary on x86.
