### ISSUE TITLE
feat: Configure optimizing thread in runtime

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#195]
It's currently in index build option, better to be able to change in runtime

**Comment by cutecutecat** [comment]
Update: now the design for this is a seperated function to control `optimizing thread` for each index:
```sql
select alter_vector_index("t_idx", 'optimizing.optimizing_threads', 100);
```

**Comment by usamoi** [comment]
We may move this feature to milestone `v0.3.0`.
