### ISSUE TITLE
How to do a clean install from scratch of the extension?

### ISSUE THREAD

**Issue by dnlldl** [tensorchord/pgvecto.rs#199]
I installed the latest version of pgvecto.rs but the app I'm using requires specifically v0.1.11, however I'm now having issues because there are still traces of the latest version. https://github.com/immich-app/immich/issues/5731#issuecomment-1858687776

This is what I tried so far before installing v0.1.11 from source.

```
vm-dev:~ # rm -rf /var/lib/pgsql/data/pg_vectors
vm-dev:~ # rm /usr/lib/postgresql14/lib64/vectors.so
vm-dev:~ # rm /usr/share/postgresql14/extension/vectors.control
vm-dev:~ # rm /usr/share/postgresql14/extension/vectors--0.1.1.sql
vm-dev:~ # rm /usr/share/postgresql14/extension/vectors--0.0.0.sql
vm-dev:~ # rm -rf /root/.rustup/toolchains/*
vm-dev:~ # rm -rf /var/lib/pgsql/.rustup/toolchains/*
```

However the errors in the app are still present:
```
could not find function "typmod_in_wrapper" in file "/usr/lib/postgresql/14/lib/vectors.so"
```

**Comment by mertalev** [comment]
Shot in the dark, but could running this fix it? `ALTER EXTENSION vectors UPDATE TO '0.1.1';`

**Comment by gaocegege** [comment]
cc @VoVAllen

**Comment by VoVAllen** [comment]
Sorry for the problem. We're preparing a patch and upgrade SQL and expecting to be ready within this week. Does alter extension work for you?

**Comment by dnlldl** [comment]
I'm very happy to report that it worked.

```

immich=# DROP EXTENSION vectors;
DROP EXTENSION
immich=# CREATE EXTENSION vectors;
CREATE EXTENSION
immich=# ALTER EXTENSION vectors UPDATE TO '0.1.1';
NOTICE:  version "0.1.1" of extension "vectors" is already installed
ALTER EXTENSION
```
Restarted my app and everything is working flawlessly now.
Thank you @mertalev and @VoVAllen for your help with these small anecdotical issues, very very appreciated.

**Comment by mertalev** [comment]
Happy to hear that fixed it!

@VoVAllen ALTER EXTENSION would definitely be helpful so we can do these updates automatically.

**Comment by dkerlee** [comment]
I still don't really get this. Are these commands I'm supposed to run in the postgresql15 container while connected to psql and the immichdb?

**Comment by dkerlee** [comment]
> I'm very happy to report that it worked, I was searching for a solution a little bit too complicated while the solution was in fact simple.
> 
> ```
> immich=# DROP EXTENSION vectors;
> DROP EXTENSION
> immich=# CREATE EXTENSION vectors;
> CREATE EXTENSION
> immich=# ALTER EXTENSION vectors UPDATE TO '0.1.1';
> NOTICE:  version "0.1.1" of extension "vectors" is already installed
> ALTER EXTENSION
> ```
> 
> Restarted my app and everything is working flawlessly now. Thank you @mertalev and @VoVAllen for your help with these small anecdotical issues, very very appreciated.

I still don't really get this. Are these commands I'm supposed to run in the postgresql15 container while connected to psql and the immichdb?

**Comment by dnlldl** [comment]
> I still don't really get this. Are these commands I'm supposed to run in the postgresql15 container while connected to psql and the immichdb?

That's exactly what I did yes, however my PostgreSQL instance is not in a docker so YMMV.
