### ISSUE TITLE
Bug on DSM 7.2

### ISSUE THREAD

**Issue by N1ck01as** [tensorchord/pgvecto.rs#202]
Hello,
I'm using pgvecto.rs on DSM 7.2 but I can't run docker container due to an error: 

2023-12-19 01:45:55.529 UTC [41] ERROR:  called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }
immich_postgres          | 2023-12-19 01:45:55.529 UTC [41] STATEMENT:  
immich_postgres          | 	      CREATE INDEX IF NOT EXISTS clip_index ON smart_search
immich_postgres          | 	      USING vectors (embedding cosine_ops) WITH (options = $$
immich_postgres          | 	      [indexing.hnsw]
immich_postgres          | 	      m = 16
immich_postgres          | 	      ef_construction = 300
immich_postgres          | 	      $$);
immich_postgres          | 2023-12-19 01:46:11.483 UTC [42] ERROR:  called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }
immich_postgres          | 2023-12-19 01:46:11.483 UTC [42] STATEMENT:  
immich_postgres          | 	      CREATE INDEX IF NOT EXISTS clip_index ON smart_search
immich_postgres          | 	      USING vectors (embedding cosine_ops) WITH (options = $$
immich_postgres          | 	      [indexing.hnsw]
immich_postgres          | 	      m = 16
immich_postgres          | 	      ef_construction = 300
immich_postgres          | 	      $$);
immich_postgres          | 2023-12-19 01:46:30.230 UTC [44] ERROR:  called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }
immich_postgres          | 2023-12-19 01:46:30.230 UTC [44] STATEMENT:  
immich_postgres          | 	      CREATE INDEX IF NOT EXISTS clip_index ON smart_search
immich_postgres          | 	      USING vectors (embedding cosine_ops) WITH (options = $$
immich_postgres          | 	      [indexing.hnsw]
immich_postgres          | 	      m = 16
immich_postgres          | 	      ef_construction = 300
immich_postgres          | 	      $$);

I don't know how to solve it...
Many thanks

**Comment by usamoi** [comment]
Can you provide your kernel version? You can get it with `uname -a`.

**Comment by N1ck01as** [comment]
> Can you provide your kernel version? You can get it with `uname -a`.

Linux y0shi 3.10.108 #64570 SMP Fri Jun 2 23:36:41 CST 2023 x86_64 GNU/Linux synology_braswell_416play

**Comment by usamoi** [comment]
The mininal Linux version we support is 3.17 I think. We will have a patch to allow the extension to work on 3.10 later today.

**Comment by N1ck01as** [comment]
Thank you! It would be nice ^^

**Comment by remowashere** [comment]
Same issue on Synology RS1219+ rackserver, upgrading any release after [v1.90.2](https://github.com/immich-app/immich/releases/tag/v1.90.2) results in a broken Immich installation

Linux rackserver 3.10.108 #64216 SMP Tue Mar 7 17:11:48 CST 2023 x86_64 GNU/Linux synology_avoton_rs1219+

**Comment by bubblesnout** [comment]
Was looking at migrating from PhotoPrism to Immich today since I keep hearing so many good things about it but I'm having this issue trying to start the container too.

Synology DS916+ running latest OS (DSM 7.2-64570 Update 3)
