### ISSUE TITLE
chore: Benchmark

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#21]
Maybe we could use https://github.com/qdrant/vector-db-benchmark to benchmark it

**Comment by gaocegege** [comment]
We have a simple bench here https://github.com/usamoi/pgvecto.rs-bench

**Comment by cutecutecat** [comment]
> Or add it to https://github.com/zilliztech/VectorDBBench

I think it's a good idea as they have a easy-to-use WebUI and benchmark board.
I have worked on it: https://github.com/zilliztech/VectorDBBench/pull/242

**Comment by VoVAllen** [comment]
Tracked in #216
