### ISSUE TITLE
feat(deployment): Research PG on Kubernetes

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#211]
- https://github.com/cloudnative-pg/cloudnative-pg
- https://github.com/zalando/postgres-operator

**Comment by gaocegege** [comment]
We should investigate if it is possible to run pgvecrto.rs and pg on kubernetes with the help of these operators.

**Comment by mertalev** [comment]
For CloudNativePG, you can also take a look at this repo: https://github.com/bo0tzz/cnpgvecto.rs

**Comment by gaocegege** [comment]
> For CloudNativePG, you can also take a look at this repo: https://github.com/bo0tzz/cnpgvecto.rs

Wow, Big thanks! cc @xieydd

**Comment by gaocegege** [comment]
> For CloudNativePG, you can also take a look at this repo: https://github.com/bo0tzz/cnpgvecto.rs

Do you need to deploy the extension on Kubernetes? I used to think immich users mainly deploy the server on cloud VMs or the NAS.

**Comment by mertalev** [comment]
We have a decent number of Kubernetes users. They tend to be power users who deploy a bunch of self-hosted services and share the same Postgres operator for all them.

I honestly don't know if I can say there's a "main" way people deploy Immich at this point 😅 I've seen everything from elaborate clusters with Xeons or Threadrippers, NAS deployments (Unraid, TrueNAS, etc.), gaming PCs, Raspberry Pis and even someone who deployed on an OpenWRT router. We just do our best to make it work for everyone.

**Comment by gaocegege** [comment]
Thanks for your explanation!

**Comment by gaocegege** [comment]
CNPG works well.

Here are some TODOs:

- Test logical replication on K8s
- Add documentation to https://github.com/tensorchord/pgvecto.rs-docs

**Comment by gaocegege** [comment]
@xieydd We could please the k8s-related doc in https://github.com/tensorchord/pgvecto.rs-docs/tree/main/src/admin

**Comment by xieydd** [comment]
> @xieydd We could please the k8s-related doc in https://github.com/tensorchord/pgvecto.rs-docs/tree/main/src/admin我们可以请 https://github.com/tensorchord/pgvecto.rs-docs/tree/main/src/admin 中的 k8s 相关文档

ok, I will add the documents to the repository this week.

**Comment by xieydd** [comment]
> CNPG works well. CNPG 运作良好。
> 
> Here are some TODOs:以下是一些待办事项：
> 
> * Test logical replication on K8s在 K8s 上测试逻辑复制
> * Add documentation to https://github.com/tensorchord/pgvecto.rs-docs将文档添加到 https://github.com/tensorchord/pgvecto.rs-docs

I have tested logical replication on pgvector and pgvecto.rs.
pgvector's logical replication is fine. However, pgvecto.rs currently does not seem to support logical replication and streaming replication. Both of these rely on WAL and logical decoding.

It may still need to implement Custom WAL Resource Managers as mentioned [here](https://github.com/tensorchord/pgvecto.rs/issues/147#issuecomment-1867678824).

**Comment by xieydd** [comment]
> CNPG works well.
> 
> Here are some TODOs:
> 
> * Test logical replication on K8s
> * Add documentation to https://github.com/tensorchord/pgvecto.rs-docs

I have tested logical replication on pgvector and pgvecto.rs.
pgvector's logical replication is fine. However, pgvecto.rs currently does not seem to support logical replication and streaming replication. Both of these rely on WAL and logical decoding.

It may still need to implement Custom WAL Resource Managers as mentioned [here](https://github.com/tensorchord/pgvecto.rs/issues/147#issuecomment-1867678824).

**Comment by gaocegege** [comment]
cc @VoVAllen

**Comment by VoVAllen** [comment]
FDW, logical replication
