### ISSUE TITLE
chore: Unit test for more scenarios

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#215]
Test:
- [x] Crash Recovery
- [x] Partition index (CREATE TABLE items (embedding vector(3), category_id int) PARTITION BY LIST(category_id);
- [x] Partial index (`CREATE INDEX ON items USING ivfflat (embedding vector_l2_ops) WITH (lists = 100) WHERE (category_id = 123);`)
- [x] Multiple index on single column
- [x] Reindex + Reindex Concurrently
- [x] Drop index when indexing

**Comment by cutecutecat** [comment]
Discussion with @xieydd 

## Partition index
If two indexes are created at both child and parent table of `PARTITION`, which would be used in the query?

## Pgvector test format
pgvector uses `Tap Tests` to write tests not directly for `getting output`.
As for our `Concurrent` Test, it could not be easily handled by `sqllogictest`, as its target is output of single statement, not interaction.
> [Sqllogictest](https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki) is a testing framework to verify the correctness of an SQL database.

We need to discuss whether to introduce these framework.
ref: https://www.postgresql.org/docs/current/regress-tap.html

## Multiply index at column
If multiply indexes are created, which index would be used at query?

#

**Comment by xieydd** [comment]
I think `reindex` and `reindex concurrently` is already supported. https://github.com/tensorchord/pgvecto.rs/blame/main/tests/sqllogictest/reindex.slt#L26

**Comment by usamoi** [comment]
I have an idea that bgworker works independently so that we can just test bgworker without considering PostgreSQL stuff.
