### ISSUE TITLE
chore: Check release on ARM

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#219]

**Comment by gaocegege** [comment]
Could you please elaborate on what should be done for the issue?

**Comment by VoVAllen** [comment]
@gaocegege We don't have ci test on arm, and it's compiled with cross-compilation. This issue only includes manual testing I think. We need to test it manually on arm before release

**Comment by usamoi** [comment]
I have tried compiling with docker and QEMU. It takes about 90 minutes to build an aarch64 release while it takes less than 10 minutes to build a x86_64 release. We should setup an aarch64 machine for compilation or aarch64 releases should be removed in nightly releases.

**Comment by VoVAllen** [comment]
- Check whether cross compilation work
- Test on ARM

**Comment by cutecutecat** [comment]
# Test on ARM - steps
- install `pg` at ubuntu AWS `a1.xlarge` arm64
- install [v0.0.0-nightly.20240123](https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.0.0-nightly.20240123)
- run sqllogictest -> passed

Minimum estimate storage assigned: 16G

- [ ] pg-12
- [ ] pg-13
- [x] pg-14
- [ ] pg-15
- [ ] pg-16
