### ISSUE TITLE
chore: More installation methods 

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#236]
> You can also install it with [Docker](https://github.com/pgvector/pgvector#docker), [Homebrew](https://github.com/pgvector/pgvector#homebrew), [PGXN](https://github.com/pgvector/pgvector#pgxn), [APT](https://github.com/pgvector/pgvector#apt), [Yum](https://github.com/pgvector/pgvector#yum), or [conda-forge](https://github.com/pgvector/pgvector#conda-forge), and it comes preinstalled with [Postgres.app](https://github.com/pgvector/pgvector#postgresapp) and many [hosted providers](https://github.com/pgvector/pgvector#hosted-postgres). There are also instructions for [GitHub Actions](https://github.com/pgvector/setup-pgvector).

pgvector supports multiple installation methods.

**Comment by xieydd** [comment]
I did some research on how to install `pgvecto.rs` through [PostgreSQL APT Repository](https://wiki.postgresql.org/wiki/Apt), and the summary is as follows:
- Opened an ITP bug for pgvecto.rs
- Used `dh make_pgxs` to build the initial source package
- Addressed all FIXMEs in the initial source package
- Verified the package builds locally w/ sbuild
-  Created new project on salsa.debian.org/postgresql, update CI/CD settings to point d/gitlab-ci.yml
- Added a job for pgvecto.rs to the pgapt Jenkins jobs (attached as a patch)

Reference:
- https://www.postgresql.org/message-id/CAFi4Z0zJBF+Lup1kSpBXKxGf1H27VR7v3FUVOuAE4As+GiNgwA@mail.gmail.com
- https://www.postgresql.org/message-id/CAOMoQbQ+kXEOgaT1WUya9vf78a4Hmi13sNuHz2sEXVvjcMasRQ@mail.gmail.com
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034391

**Comment by xieydd** [comment]
ITP bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064176
