### ISSUE TITLE
discussion: 24 Q1 Q2 Roadmap

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#243]
2024 Q1, Q2 planning

- [puck index](https://github.com/baidu/puck) (Higher density on the disk)
  - Better KMeans computation / Minibatch Kmeans
- In-memory Vamana index (Better support for update and delete) (Simplified version of DiskANN)
  - With vectors on the disk (support io_uring) and graph in the memory
  - Partitioned build within constrained memory
- Sparse vector support (Hybrid search)
- Quantization / Low precision
  - Binary quantization
  - Oversample + Rerank to improve final results

**Comment by gaocegege** [comment]
Could you please explain more about the spare support? Why do we need this.

**Comment by kemingy** [comment]
What's the purpose of the binary quantization? Does it work without the embedding model quantization aware training?

**Comment by VoVAllen** [comment]
Sparse vector can be used in hybrid search like https://qdrant.tech/articles/sparse-vectors/. SPLADE is a sparse vector model, which can improve the retrieval diversity and quality.

**Comment by VoVAllen** [comment]
Binary quantization has a very limited scenarios, that needs to be considered during the embedding model training process. Some [experiments](https://colab.research.google.com/drive/1-bh7s_VmsE44CSOE554Jvf6DdOVWdHD1?usp=sharing#scrollTo=I8eE5H1-K0nC) showed that binary quantization + oversample with OpenAI models can still achieve high recall rate.

**Comment by gaocegege** [comment]
We get some requests for DiskANN: https://github.com/tensorchord/pgvecto.rs/issues/173 / https://github.com/tensorchord/pgvecto.rs/issues/173

Do we have plan to support it?

**Comment by VoVAllen** [comment]
In-memory vamana is a simpler variant of DiskANN. DiskANN stores graph and vectors both on graph, but in-memory vamana uses memory to store graph. It's more costly but easier to implement with reasonable capacity. The scenarios of DiskANN use a super small machine for a super large dataset is not common in real scenarios. The index building time for diskann is 4 days for a 100M 96dim dataset, which is not ideal.

**Comment by gaocegege** [comment]
SGTM

**Comment by VoVAllen** [comment]
Move to documentation
