### ISSUE TITLE
feat(docs): Integration doc with Langchain / LlamaIndex

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#245]

**Comment by BeautyyuYanli** [comment]
- https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/vectorstores/pgvecto_rs.ipynb
- https://github.com/run-llama/llama_index/blob/main/docs/examples/vector_stores/PGVectoRsDemo.ipynb

**Comment by gaocegege** [comment]
Sorry for the misunderstanding. I mean we should add corresponding docs in our own doc website.

https://docs.pgvecto.rs/getting-started/overview.html

**Comment by gaocegege** [comment]
I will create doc for langchain first.

**Comment by gaocegege** [comment]
I will add llama index today.
