### ISSUE TITLE
`DROP INDEX CONCURRENTLY` behavior changes with the extension preloaded

### ISSUE THREAD

**Issue by nebulade** [tensorchord/pgvecto.rs#253]
For some context, we have a scenario where the postgres database is shared with multiple apps on Cloudron. Since Immich requires this extension by now, we have added it to the postgres instance and preload it with:
```
ALTER SYSTEM SET shared_preload_libraries = 'vectors.so'
```
Unfortunately this has the side-effect that in our case a discourse installation fails to run a `DROP INDEX CONCURRENTLY` with the error:
```
PG::FeatureNotSupported: ERROR: DROP INDEX CONCURRENTLY must be first action in transaction
```
If we do not preload `vectors.so` it works fine.

I lack the insights into postgres and plugins, but I have seen that tests may be lacking for DROP INDEX while adding an index with CONCURRENTLY has tests https://github.com/tensorchord/pgvecto.rs/blob/4bdf192412ffbd16c74596ee0193b74e3630721a/tests/sqllogictest/update.slt#L11

It would already greatly help if someone could share some info on if this a bug or expected behavior and if so, if future versions would fix this. 

Let me know if you need more detailed information or want me to run some tests. Thanks!

**Comment by usamoi** [comment]
We had a hook about `DROP INDEX` before and it was removed in https://github.com/tensorchord/pgvecto.rs/commit/d5954e6b4a88fd2ff2e36ce183d5edf33e0ca730 (2023/11/24). Can you give the version/commit of pgvecto.rs?

**Comment by nebulade** [comment]
We use currently 0.1.11 since that is what Immich required at least last time we looked at that.

**Comment by usamoi** [comment]
0.1.11 is the last version that does not include the https://github.com/tensorchord/pgvecto.rs/commit/189fe96b1d417347b695b99937ca785cc5400907. I think there is no problem if you use latest version.

**Comment by usamoi** [comment]
We will release 0.2.0 version in January and it's recommended for you to just update to 0.2.0 when it releases.

**Comment by nebulade** [comment]
Great thanks for the confirmation, then we will just wait for the new version to be cut and we should be good.
