### ISSUE TITLE
Rootless image

### ISSUE THREAD

**Issue by Y0ngg4n** [tensorchord/pgvecto.rs#261]
Please provide a image that does not need to run as root. :)

**Comment by usamoi** [comment]
Did you read the "Arbitrary --user Notes" section in https://hub.docker.com/_/postgres and is it helpful?

**Comment by VoVAllen** [comment]
According to my understanding, is this (https://github.com/cloudnative-pg/postgres-containers/blob/main/Debian/16/Dockerfile#L55-L57) what we need?

**Comment by VoVAllen** [comment]
cc @gaocegege , What's the best practice to build a rootless container image?

**Comment by Y0ngg4n** [comment]
@VoVAllen the problem is that in a kubernetes environment you are often not able to run containers with root if installed via a helm chart that does not support that. so the best practice would be to start the container not with the root user and instead create a postgres user that runs the container.

**Comment by Y0ngg4n** [comment]
> According to my understanding, is this (https://github.com/cloudnative-pg/postgres-containers/blob/main/Debian/16/Dockerfile#L55-L57) what we need?

yes exactly :)

**Comment by gaocegege** [comment]
> cc @gaocegege , What's the best practice to build a rootless container image?

Just as you commented before.

We could add one in v0.2.0 release. Thanks for raising this! @Y0ngg4n

**Comment by Y0ngg4n** [comment]
@gaocegege when will 0.2.0 get approximately released?

**Comment by VoVAllen** [comment]
@Y0ngg4n We plan to release it next week, no later than the end of this month.

**Comment by Y0ngg4n** [comment]
@VoVAllen thanks :)

**Comment by gaocegege** [comment]
@VoVAllen Should we add a new tag for rootless, or just replace the current image (root user) with the rootless implementation?

Personally prefer keeping both root and rootless.

cc @xieydd

**Comment by VoVAllen** [comment]
I think we put it as a seperate image, avoid breaking current settings

**Comment by Y0ngg4n** [comment]
@VoVAllen where do i find the image?

**Comment by gaocegege** [comment]
@Y0ngg4n We added it to the CD process. We should release a new version to trigger it cc @VoVAllen

**Comment by gaocegege** [comment]
https://hub.docker.com/layers/tensorchord/pgvecto-rs/pg15-v0.2.0-alpha.1-rootless/images/sha256-461eb89ba4a2f35c48d4fbbce8d22222691a55dc4fb60c1fe1cc2fe9ee44f569?context=repo @Y0ngg4n It should work.

**Comment by Y0ngg4n** [comment]
@gaocegege no pg16 image?

**Comment by gaocegege** [comment]
Here is the rootless image for 16: https://hub.docker.com/layers/tensorchord/pgvecto-rs/pg16-v0.2.0-alpha.2-rootless/images/sha256-e2ac97b97aca96b26da3941c0fd0d1746f1a2737922005f3ca84ef14b7d854ca?context=repo

**Comment by gaocegege** [comment]
YOu could get all from here: https://hub.docker.com/repository/docker/tensorchord/pgvecto-rs/tags?page=1&ordering=last_updated&name=rootless
