### ISSUE TITLE
feat: Function / cast to convert vectors into vecf16

### ISSUE THREAD

**Issue by JoePassanante** [tensorchord/pgvecto.rs#262]
Hey folks,

My database currently has a 100k+ vectors, I need to reduce my memory usage before expanding further.   Ideally, I don't want to re compute these vectors from scratch nor write a script that moves that vectors into the vecf16 type. 

```SQL
ALTER TABLE "tableName"
ALTER COLUMN "embedding"
TYPE vecf16
USING embedding::vecf16
```

```
Error in query: ERROR: cannot cast type vector to vecf16
LINE 4: USING embedding::vecf16
```

Would it be possible to add an explicit cast, or function that allows this?

**Comment by JoePassanante** [comment]
I think I can take this one. 

Going to introduce a new CAST 

```SQL
CREATE CAST (vector AS vecf16)
    WITH FUNCTION _vectors_cast_vecf32_to_vecf16(vector, integer, boolean) AS IMPLICIT;
```

and introduce a new fn in casts_f32.rs.

**Comment by usamoi** [comment]
Tracking in #255.
