### ISSUE TITLE
target of 32 bit is not supported, or document needs note it

### ISSUE THREAD

**Issue by njhsi** [tensorchord/pgvecto.rs#269]
Trying to cross build this extension for target armv7l@openwrt on host x86-64@debian, finally got to compiling vectors.so, but failed with error as below.

Would be great if some info was given in advance that 32 bit target is not supported or yes but how. Anyway, thanks a lot!

==build log===
error: Target is not supported.
  --> src/lib.rs:52:1
   |
52 | compile_error!("Target is not supported.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:4:12
  |
4 | #![feature(core_intrinsics)]
  |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `vectors` (lib) due to 2 previous errors

====src/lib.rs===
#[cfg(not(target_pointer_width = "64"))]
compile_error!("Target is not supported.");

**Comment by usamoi** [comment]
The mainly reason why we forbid 32-bit targets:
* we have no tests on 32-bit targets
* there might be some integer overflow if `usize` is only 32-bit

**Comment by usamoi** [comment]
If you want to try pgvecto.rs, just remove `#[cfg(not(target_pointer_width = "64"))] compile_error!("Target is not supported.");` and compile. It's probably OKay. We advice you to follow instructions in https://docs.pgvecto.rs/developers/development.html to set up a correct build environment (`rustup` is probably needed, but it looks that you do not install it).

**Comment by workingjubilee** [comment]
pgrx is not truly tested nor designed for 32-bit CPUs, as we pervasively assume 8-byte Datums in the implementation of the library. We allow people to compile it for 32-bit as some people have expressed interest in exploring this, and apparently it "works" to some extent, but it is very likely to cause problems, as none of our primary contributors design or test their extensions for 32-bit CPUs and so we have not had a thorough evaluation of pgrx for that purpose.
