### ISSUE TITLE
feat(docs): Use cargo to install pg instead of apt get

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#284]
https://docs.pgvecto.rs/developers/development.html

We should use the pg installed by cargo run. Because pg from apt lacks debug info. The doc needs update.

cc @usamoi

**Comment by usamoi** [comment]
already fixed in https://github.com/tensorchord/pgvecto.rs/pull/265

**Comment by gaocegege** [comment]
Do we need to change doc in cross compilation?

https://docs.pgvecto.rs/developers/development.html#cross-compilation

**Comment by usamoi** [comment]
> Do we need to change doc in cross compilation?

No.
