### ISSUE TITLE
support sqlite

### ISSUE THREAD

**Issue by nick008a** [tensorchord/pgvecto.rs#298]
any chance pgvecto becomes sqlitevecto?

**Comment by VoVAllen** [comment]
Compared to Postgres, SQLite has different design goals as an embedded database, which affects the storage design of vector indexes. This makes code reuse difficult. Additionally, SQLite does not support Rust plugin development, so currently we do not have any plan to support SQLite.

**Comment by cutecutecat** [comment]
There are some recently appeared extension framework for Rust to build a loadable extension for `sqlite`:
- [sqlite-loadable-rs](https://github.com/asg017/sqlite-loadable-rs)
- [rusqlite.loadable_extension](https://github.com/rusqlite/rusqlite)

And there is some exist vector extension for `sqlite`:
- [sqlite-vss](https://github.com/asg017/sqlite-vss)

But it seems that sqlite extension is much different from pg extension, as it doesn't hook statement plan, but uses seperated virtual table and register its handler. 

We will keep an eye on them continually, and do some research whether they are available for production.
