### ISSUE TITLE
Upgrading from 0.1.x to 0.2 with only SQL commands

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#312]
Hi! I'm working on the upgrade logic to 0.2 and noticed there's a step to run `rm -rf $(psql -U postgres -tAqX -c 'SHOW data_directory')/pg_vectors` and restart the container. This is a bit scary to run so we're trying to find a way to do the upgrade without this.

Right now, we're considering an approach where we drop indices, convert columns to `real[]` and drop the extension, all with an instance still running 0.1.11. Then we can (presumably) upgrade to an instance with 0.2 without needing to manually delete files.

But ideally, we would like to be able to upgrade without pre-requisite steps on an instance with 0.1.11. Is it feasible for you to make the upgrade path more graceful so we can upgrade without `rm -rf` or this workaround?

**Comment by VoVAllen** [comment]
We discussed and decided to provide an SQL function to help users clean up old versions of files. We will prepare a new version that includes this update today or tomorrow.

**Comment by mertalev** [comment]
Thank you so much! This will make the upgrade much simpler.

**Comment by VoVAllen** [comment]
We've just released 0.2.0-alpha.1. The upgrade process now is:
- `ALTER EXTENSION vectors UPDATE TO 0.2.0-alpha.1` (should be 0.2.0 for the final version)
- `SELECT pgvectors_upgrade();`
- REINDEX the vector columns

Feel free to raise new issues if you encounter any problems!
