### ISSUE TITLE
feat: Publish image with tags start with a valid PostgreSQL major version number (e.g. 14.5 or 15)

### ISSUE THREAD

**Issue by geneliu** [tensorchord/pgvecto.rs#317]
The published image on docker hub has tags with prefix 'pg'. 
[Docker image](https://hub.docker.com/r/tensorchord/pgvecto-rs)

There is a need to create cluster from those images by cloudnative-pg operator. 

The operator has the tag requirements:
The image tag must start with a valid PostgreSQL major version number (e.g. 14.5 or 15).

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/container_images.md#image-tag-requirements

**Comment by xieydd** [comment]
@geneliu To ensure that you can use pgvecto.rs in the `cloudnative-pg` environment, we maintain a [repository](https://github.com/tensorchord/cloudnative-pgvecto.rs). To be used with the Kubernetes CloudNativePG operator, the `cloudnative-pgvecto.rs` image and pgvecto.rs image are slightly different, and we have temporarily placed them on [ghcr.io](https://github.com/tensorchord/cloudnative-pgvecto.rs/pkgs/container/cloudnative-pgvecto.rs). The tags of these images  start with a valid PostgreSQL major version number.

**Comment by gaocegege** [comment]
@xieydd We already configured the docker hub related secrets in the repository. Could we migrate to docker hub?

**Comment by xieydd** [comment]
> @xieydd We already configured the docker hub related secrets in the repository. Could we migrate to docker hub?

lgtm, I will migrate it to the docker hub.

**Comment by xieydd** [comment]
I think @bo0tzz has already config the ci for pushing the image to the docker hub.

@geneliu https://hub.docker.com/r/tensorchord/cloudnative-pgvecto-rs/tags

**Comment by gaocegege** [comment]
Thanks, we already have it in DockerHub: https://hub.docker.com/r/tensorchord/cloudnative-pgvecto-rs

**Comment by geneliu** [comment]
Looks good. Thank you everyone.
