### ISSUE TITLE
feat: Support vector prefix chunk when indexing

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#327]
The latest OpenAI embedding support using subvector as dimension reduction. User should be able to index the vectors based on that like 
```SQL
create index on items using vectors (prefix_chunk(embedding, 64) vector_l2_ops) 
```

Reference: https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-dimensions

**Comment by usamoi** [comment]
I think it can be supported by creating an index on expression.

**Comment by usamoi** [comment]
Completed in #329 

Should we document it now? (We do not release documentation with software so users may read text about a feature that is not implemented in `2.0`)

**Comment by usamoi** [comment]
Document is tracking in #255 and #358

**Comment by gaocegege** [comment]
How could I use this feature? Do we have a pre-release for it? I am writing the benchmark for it.

**Comment by VoVAllen** [comment]
@gaocegege `CREATE INDEX t_vector_index on t using vectors((val[0:128]::vector(128)) vector_l2_ops);` to create index on prefix 128 dim. I think the doc is missing now 😢

**Comment by gaocegege** [comment]
Would you mind creating a pre-release for test purpose?

**Comment by VoVAllen** [comment]
Let me check how I can do this. Probably to include #368 also. And I just realized the nightly docker image doesn't work now.

**Comment by gaocegege** [comment]
OK, then let's wait for #368

**Comment by usamoi** [comment]
When will we fix nightly releases?

**Comment by VoVAllen** [comment]
tracked in https://github.com/tensorchord/pgvecto.rs/issues/373
