### ISSUE TITLE
discussion: make vbase as default search mode

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/pgvecto.rs#330]
There is few situations where `basic` is better from `vbase`:
- A large Limit with tight filter, which returns too few result, where `vbase` will search the whole graph
- An extreme memory limit

In most cases, `vbase` would be better, we could make it the default search mode.

**Comment by VoVAllen** [comment]
I also feel vbase is much better than basic mode in most scenarios. 

Some concerns:
- When benchmarking, the settings are not consistent with other libraries.
- Probably not work well with IVF
- When users need higher accuracy, simply increasing ef_search may not be useful. (for example 0.01 scenarios in https://github.com/silver-ymz/pgvectors-benchmark-results, however I believe this scenario is rare)

Does vbase currently take effect with ivf @usamoi ?

**Comment by usamoi** [comment]
IVF behaviors are same on both `basic` and `vbase`.

**Comment by VoVAllen** [comment]
I'm fine setting vbase as default. @usamoi What do you think?

**Comment by usamoi** [comment]
Yes. I think it's fine too.

**Comment by VoVAllen** [comment]
@usamoi Can you make a PR for this? We can merge it before 0.2.0 release
