### ISSUE TITLE
feat: Auto-generate embedding when inserting the row

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#331]
It would be better if we could support generating embeddings in the DB for the text field.

```sql
CREATE TABLE items (
    ...,
    content text,
    embedding vector(n) GENERATED ALWAYS AS (generate_embedding(content)) STORED
);
```

For example, create a table called "items" with a column named "content" of type "text", and another column named "embedding" of type "vector(n)" that is generated based on the "content" column using a function called "generate_embedding". The "embedding" column is marked as [https://www.postgresql.org/docs/current/ddl-generated-columns.html]("GENERATED ALWAYS AS STORED").

Not sure if generated column supports a func call. We can create an AFTER INSERT OR UPDATE trigger on the table that calls the function to calculate the value and updates the column accordingly if it is not supported.

```sql
CREATE OR REPLACE FUNCTION update_embedding_column()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.embedding := generate_embedding(NEW.content);
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER calculate_embedding
BEFORE INSERT OR UPDATE ON items
FOR EACH ROW
EXECUTE FUNCTION update_embedding_column();
```

We could first implement the func `generate_embedding` and corresponding config for OpenAI embedding model. Then write a doc to show how to do it.

**Comment by usamoi** [comment]
Generated column needs an immutable expression. Vectorizers must be marked `volatile` because there are IO operations. We may only take advantages of triggers.

**Comment by cutecutecat** [comment]
As Part of this work, #350 implement new functions:
`text2vec_openai('input', 'model-name') -> vector` for user specified model.
`text2vec_openai_v3('input') -> vector` for most modern official model `text-embedding-3-small`

**Comment by usamoi** [comment]
We may need to guide users to create another table to insert vectors.

See also #346.

**Comment by cutecutecat** [comment]
After #350 ,there seems not worthing for E2E embedding retrieval at database itself. They will be implemented outside.
