### ISSUE TITLE
design: Rerank

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#335]
We need to provide some built-in rerankers e.g. model-based rerankers and fresness.

**Comment by kemingy** [comment]
Different ranking methods require more metadata than the doc itself, i.e. `updated_at`, `vector`, `quality_score` (not the similarity score).

This requires a structure to represent. Although these metadata are not mandatory.

The interface is like `reranker.rank(query, docs)` that will apply all predefined rankers sequentially. 

Rankers can be:
- cross-encoder models
- time decay (similar to the [HackerNews ranking algorithm](https://vigneshwarar.substack.com/p/hackernews-ranking-algorithm-how))
- diversity ([Maximal Marginal Relevance](https://www.cs.cmu.edu/~jgc/publication/The_Use_MMR_Diversity_Based_LTMIR_1998.pdf))
- etc.

I have implement the basic interface [here](https://github.com/kemingy/reranker)

**Comment by kemingy** [comment]
## End-to-end RAG

- data source: notes, webpages, docs, etc.
- ETL:
  - vector embedding (option: use PCA to reduce the dim)
  - inverted index
  - structured metadata (time, author, tag, etc. used for filtering & reranking)
- storage
  - snapshot + update
  - authorization
- hybrid search:
  - vector similarity search (order by distance)
  - full-text search (order by BM25/TF-IDF)
- reranking
  - cross-encoder
  - rule-based
- user feedback & a/b test

**Comment by VoVAllen** [comment]
text-based end2end SDK

- Insert text
- Query by text
- Configurable intermediate step

**Comment by VoVAllen** [comment]
- end2end latency
- documentation
- sparse vector integration (fastembed/bge-m3)
