### ISSUE TITLE
`pg_vector_index_stat` metrics don't seem to be accurate

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#346]
The number of tuples it lists increases as more searches are done even though there are no rows being added to the table. A table with 418442 rows is reported to have 694850 tuples with 680475 sealed, 14375 written and a size of 1500606072. Postgres is using about 1 gigabyte of RAM, so that figure seems off.

While writing, the number of tuples increased to 708446 with 20000 in a growing segment. It is actually indexing the growing segment, looking at CPU usage. If I pause searches, the number stops changing.

For reference, this is with 0.2.0.

**Comment by usamoi** [comment]
Are there any `UPDATE`s, `DELETE`s and `INSERT`s in aborted transactions, in this table? If many tuples are removed, `pg_vector_index_stat` reports all stored tuples so the shown number will be bigger than the number of tuples in the table.

**Comment by mertalev** [comment]
There are no deletes or inserts, but each search updates a column in a row in this table. That explains why the number was increasing proportionately to the number of searches. Also, is the reason for the reindexing because a column is being updated? I thought it would only reindex if the vector column changes.

**Comment by usamoi** [comment]
It depends. In PostgreSQL, if a row is updated and its physical pointer changes, PostgreSQL will tell all indexes there is a new row so the row will be reinserted to all indexes in this table. It's a frequently asked questions in PostgreSQL.

I'm not sure, but the following SQL may help if you want to do more tests.

```sql
ALTER TABLE t ALTER COLUMN v SET STORAGE EXTERNAL;
```

**Comment by mertalev** [comment]
Ahh, thanks for that explanation! I set the storage to external, set fillfactor to 80 and ran `VACUUM FULL`. The number of tuples matches the table size now. Unfortunately it looks like the updates are still creating new rows, but I can at least confirm this isn't a pgvecto.rs issue at this point.
