### ISSUE TITLE
There is an extension for hnsw + pg, but it is write by c/c++

### ISSUE THREAD

**Issue by zhuwenxing** [tensorchord/pgvecto.rs#35]
https://github.com/neondatabase/pg_embedding

**Comment by VoVAllen** [comment]
Yes. We've studied this project today. And we found it's index is not persistent, which means reindex is needed for every session

**Comment by zhuwenxing** [comment]
Right！ It is still an experimental project. 
I found it from https://news.ycombinator.com/item?id=36695542, and someone also points out this.
