### ISSUE TITLE
feat: Support binary representation in python SDK

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#354]
Inserting data in binary representation significantly accelerates performance in PostgreSQL. But it is hard to write in python. We should support it in SDK

Could you please put the sample python code in the issue? @VoVAllen

**Comment by VoVAllen** [comment]
Possibly with this feature https://www.psycopg.org/psycopg3/docs/basic/copy.html

**Comment by cutecutecat** [comment]
## Requirement
https://github.com/pgvector/pgvector-python/blob/913fbb0dcb1e3e98f0b748cc0ad09c8ddd7fac05/requirements.txt#L6

## Library
https://github.com/pgvector/pgvector-python/blob/913fbb0dcb1e3e98f0b748cc0ad09c8ddd7fac05/pgvector/utils/__init__.py#L13

https://github.com/pgvector/pgvector-python/blob/913fbb0dcb1e3e98f0b748cc0ad09c8ddd7fac05/pgvector/psycopg/__init__.py#L36

## Test
https://github.com/pgvector/pgvector-python/blob/913fbb0dcb1e3e98f0b748cc0ad09c8ddd7fac05/tests/test_psycopg.py#L28

**Comment by my-vegetable-has-exploded** [comment]
I write a little example here. https://github.com/tensorchord/pgvecto.rs/compare/main...my-vegetable-has-exploded:pgvecto.rs:binary-copy?expand=1

Here is a example result on my machine.

```
example result:
Insert 1000 rows in 154.197 millseconds
1000
Bytes size: 6152021 > (dims * 4 + 2) * rows
Copy 1000 rows by block in 26.903 millseconds
1000
Copy 1000 rows by row in 26.125 millseconds
1000
Write 1000 rows to parquet in 55.226 millseconds
```

**Comment by my-vegetable-has-exploded** [comment]
Here is on-cpu flamegraph of postgres using 400000 rows.

https://gist.github.com/my-vegetable-has-exploded/b8b72a10d07023f82a0090257bb1e3a9
