### ISSUE TITLE
feat: Binary vector support 

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#355]
Support binary vector type and user can use it to build the index.

[Benchmark](https://twitter.com/NirantK/status/1755135939901628877/photo/1) result from Qdrant:
![image](https://github.com/tensorchord/pgvecto.rs/assets/8686776/86429cfb-4d3c-4dab-b835-34e19b39834a)

**Comment by gaocegege** [comment]
Is it related to #354

**Comment by VoVAllen** [comment]
No. binary representation is the binary format for each type. This is a new data type

**Comment by silver-ymz** [comment]
I'll take it.
