### ISSUE TITLE
Update to 0.2.0 ends with type "vecf16" already exists

### ISSUE THREAD

**Issue by saschabrockel** [tensorchord/pgvecto.rs#371]
I tried to do what the manual says (https://docs.pgvecto.rs/admin/upgrading.html#upgrade-from-01x) and maybe messed up the command before and now end up in the logs with:

`2024-02-21 04:56:33.753 CET [234] ERROR:  type "vecf16" already exists`

How can I fix this?

**Comment by usamoi** [comment]
Could you describe what commands do you execute?

**Comment by saschabrockel** [comment]
I use the Docker container. Then I get into the container as user 999 (postgres). In the Docker terminal I enter
`psql -h localhost -U immich` to be able to execute SQL and after that I try to run the command:

```
UPDATE pg_catalog.pg_extension SET extversion = '0.1.6' where extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true where extname = 'vectors';
ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false where extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';
```

**Comment by usamoi** [comment]
I think immrich uses `0.1.11` before. Could you replace `0.1.6` with `0.1.11` and try again?

**Comment by saschabrockel** [comment]
Returns `ERROR:  type "vecf16" already exists` as well. I hope I didn't mess it up too badly...

**Comment by usamoi** [comment]
Could you execute `select typname from pg_type where typname LIKE 'vec%' OR typname LIKE 'Vec%';`?

**Comment by saschabrockel** [comment]
```
      typname      
-------------------
 vector
 vector_index_stat
 vecf16
(3 rows)
```

**Comment by usamoi** [comment]
Not sure what you did but it's alreay updated to `2.0` so you could just execute:
```sql
UPDATE pg_catalog.pg_extension SET extversion = '0.2.0' where extname = 'vectors';
```

**Comment by saschabrockel** [comment]
I don't know either... but it works now. Thank you!

**Comment by mertalev** [comment]
I think Immich updated the extension, but running those commands set the version back to 0.1.11 (on paper). Immich tried to update the extension again since it thought you were on 0.1.11, but this failed since the extension is really already on 0.2.0.
