### ISSUE TITLE
feat: support native PostgreSQL logging format

### ISSUE THREAD

**Issue by usamoi** [tensorchord/pgvecto.rs#374]
Someone may need to parse PostgreSQL logs and do some processing. For example, `cnpg` reads PostgreSQL logs in csv format and pass them to users in JSON format.

Background worker logs do not follow PostgreSQL configuration. We need to implement a logger that follows PostgreSQL configuration.

Reference for contributors:

* https://cloudnative-pg.io/documentation/1.22/postgresql_conf/#log-control-settings
* https://www.postgresql.org/docs/current/runtime-config-logging.html

**Comment by JinweiOS** [comment]
Although I'm new to both rust and pgvecto.rs, I wanted to try the following to complete this issue. By referring to the documentation and issue #376, as well as my own experiments, I temporarily learned:

+ At this stage, bgwork ignores all errors in the `session` function.
https://github.com/tensorchord/pgvecto.rs/blob/a1e79bba571a79c574996f0e5d8b98b8dfdf8763/src/bgworker/normal.rs#L18
+ pgrx supports collecting painc and outputting the corresponding format according to the configuration of log_destination.
Therefore, errors in the bgwork session function should be thrown with painc, so that pgrx can output to the target file in json/csv/.. format. 

So I think that the error collection requirements in issue #376 can be met first by throwing the fn `session` errors. However, it should be noted here that the session is in a child thread.

I don’t know if there is any deviation in my understanding, or I would like to know more about `implement a logger that follows PostgreSQL configuration`. Is there a more detailed description to help me understand the requirements?

**Comment by usamoi** [comment]
We use [log](https://docs.rs/log/) to print logs to stderr in the background process. However, this crate does not control the output format of logs. [env_logger](https://docs.rs/env_logger/) implements [trait.Log](https://docs.rs/log/latest/log/trait.Log.html) to do actually work (format and print these logs). What we need is to write another implementation of `Log` to respect the config about logging format in `postgresql.conf`.

**Comment by JinweiOS** [comment]
I have done some testing recently and have the following thoughts on the implementation of logs.

## Current situation
The current log implementation is to redirect the logs collected by `env_logger` to stderr. When `log_destination` is set to `stderr` and `logging_collector` is `on`. if an error occurs in bgworker, it can be successfully collected. But when `log_destination` is `jsonlog`, the current solution is still to redirect the log to the `.log` log file. And even if the `log::error!` function string is in json format, it still cannot be redirected to the `.json` log file.

## Implementation plan

#### plan 1:

If I directly use the [macros](https://docs.rs/pgrx/latest/pgrx/#macros) provided by pgrx, such as `log!` and `error!`, these functions can directly accept error messages, and pgrx will automatically output the corresponding format according to the postgres configuration.

#### plan 2:

1. Read the log configuration in postgres conf;

2. Format msg according to configuration, but all fields may need to be defined by myself. For example, the following is the postgres json log format I obtained.
```json
{"timestamp":"2024-03-24 21:43:58.486 CST","pid":37650,"session_id":"66002cf0.9312","line_num":4,"session_start":"2024-03-24 21:38:56 CST","txid":0,"error_severity":"LOG","message":"checkpoint complete: wrote 18 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.745 s, sync=0.003 s, total=1.765 s; sync files=15, longest=0.002 s, average=0.001 s; distance=41 kB, estimate=41 kB","backend_type":"checkpointer","query_id":0}
```

3. Output the log information. If it is stderr, I can still use the current method to write the log; if it is json/csv, I need to manually read the current target log file path and write log msg to it. But I have not verified the feasibility of reading the file log path and writing.

I hope you can give me some more suggestions on solutions.

**Comment by usamoi** [comment]
> If I directly use the [macros](https://docs.rs/pgrx/latest/pgrx/#macros) provided by pgrx, such as `log!` and `error!`

You cannot do it. `pgrx` macros call PostgreSQL functions, which are not thread-safe[^1]. However, the background process takes advantages of multithreading: logs come from all threads. If you try it, I think `pgrx` will print an error and abort the process.

> the current solution is still to redirect the log to the `.log` log file

It's because we do not follow the protocol requested by PostgreSQL. You can follow the comments in the code.

> Format msg according to configuration, but all fields may need to be defined by myself.

Yes, we must do it.

[^1]: https://github.com/pgcentralfoundation/pgrx/blob/develop/docs/src/design-decisions.md#thread-safety

[^2]: https://github.com/postgres/postgres/blob/REL_16_STABLE/src/backend/postmaster/syslogger.c#L900

**Comment by JinweiOS** [comment]
#### Currently completed
1. Read the log_destination configuration
2. Support writing log messages(only `message`) to stderr
3. Support writing log messages(only `timestamp` & `message`) to jsonlog
4. Implemented a preliminary `logger`
[WIP](https://github.com/tensorchord/pgvecto.rs/compare/main...JinweiOS:pgvecto.rs:pglogger)
#### Some Idea
I plan to implement the writing of stderr, jsonlog and csvlog in the first stage, and then the fields will first support `timestamps`, `pid`, and `message`. At the same time, let VectorLogger support filter to be compatible with the existing writing methods in this repo.
In the second stage, all supported fields in pg log are gradually added.

#### Question
[pipe protocol](https://github.com/postgres/postgres/blob/9e6faeb3249d420a22ad8a5fbcf093b272c02cb8/src/backend/postmaster/syslogger.c#L949) need `pid`, No idea how to get this pid. I also hope you can give me some suggestions on implementation ideas.

**Comment by usamoi** [comment]
> No idea how to get this pid.

https://doc.rust-lang.org/std/process/fn.id.html should help.
