### ISSUE TITLE
Issue upgrade from 0.1.10 (thru 0.1.11) to 0.2.0

### ISSUE THREAD

**Issue by raycheung** [tensorchord/pgvecto.rs#380]
The upgrade hit https://github.com/tensorchord/pgvecto.rs/blob/main/sql/upgrade/vectors--0.1.10--0.1.11.sql#L23-L27 which would result in `ERROR: could not find function "vector_stat_wrapper" in file "/usr/lib/postgresql/16/lib/vectors.so"`. This is especially an issue when I'm using the docker image.

I ended up manually overwritten the `sql/upgrade/vectors--0.1.10--0.1.11.sql` commenting out https://github.com/tensorchord/pgvecto.rs/blob/main/sql/upgrade/vectors--0.1.10--0.1.11.sql#L23-L40
```
CREATE FUNCTION "vector_stat"(
...
```
as well as overwritten `sql/upgrade/vectors--0.1.11--0.2.0.sql` commenting out https://github.com/tensorchord/pgvecto.rs/blob/main/sql/upgrade/vectors--0.1.11--0.2.0.sql#L193 & https://github.com/tensorchord/pgvecto.rs/blob/main/sql/upgrade/vectors--0.1.11--0.2.0.sql#L463
`DROP VIEW pg_vector_index_info;` & `DROP FUNCTION vector_stat;`

**Comment by VoVAllen** [comment]
Thanks for the report. It seems we need a seperate upgrade SQL file for 0.1.10 to 0.2.0 @usamoi
