### ISSUE TITLE
Type "vector" does not exist after installing pgvecto.rs 

### ISSUE THREAD

**Issue by Caian** [tensorchord/pgvecto.rs#383]
I have a postgres 15.4 in which I manually installed pgvecto.rs 0.2.0 (it is not an upgrade). I successfully added the extension to my database, but I keep getting this error when trying to use the new "vector" type.

```
ERROR:  type "vector" does not exist
```
Postgresql log does not show any indication of error other than this one, what could be the issue?

**Comment by usamoi** [comment]
Did you add `vectors` to search path?

See also https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by njhsi** [comment]
new player, had the same question. 

what I've done:
1, **vectors.so** build ok for alpine@arm64 **musl** //exhaused:(
2, put vectors.so into pg lib path
3, put vectors--0.2.0.sql into extension folder of pg share path 
4, "CREATE EXTENSION vectors" seemed ok
5, "CREATE TABLE tests_transaction_t(val vector(3))" got error "type "**vector" does not exist**"

```
postgres=# SHOW search_path;
   search_path   
-----------------
 "$user", public
(1 row)
```

**Comment by Caian** [comment]
On the particular database I'll use vectors I did run:

```
CREATE SCHEMA IF NOT EXISTS vectors;
ALTER DATABASE my_database SET search_path TO "$user", public, vectors;
SET search_path TO "$user", public, vectors;
```

My search_path:
```
postgres=# SHOW search_path;
   search_path   
-----------------
 "$user", public, vectors
```

**Comment by njhsi** [comment]
> Did you add `vectors` to search path?
> 
> See also https://www.postgresql.org/docs/current/ddl-schemas.html

thanks for this reminding. I made it work by "SET SEARCH_PATH TO "$user", public, vectors;"

what's more I can do to verify my vectors.so works full power?

**Comment by Caian** [comment]
Another thing, the database user (unprivileged) has the same name of the database, is this an issue?

**Comment by Caian** [comment]
Only the superuser seems to be able to use the extension. I tried changing the owner of the "vectors" schema to the database user and this new error appeared: 

```
ERROR:  operator class "cosine_ops" does not exist for access method "vectors"
```

So I believe this is an issue with permissions. Google results show only people trying to create extensions as a non-superuser. I just want to use them.

**Comment by VoVAllen** [comment]
@Caian Thanks for the report. Can the non-superuser to change the search path on postgres?

**Comment by VoVAllen** [comment]
If you're not superuser, you may need to modify the search path for you by `ALTER ROLE username SET search_path TO "$user", public, vectors;`

**Comment by Caian** [comment]
Hi @VoVAllen the search path for the user itself already contained vectors.

I'm closing the issue because it was indeed a problem with permissions. I had to manually grant read/write/access permissions to the user on the vectors schema and it's individual functions. Now it is working properly.
