### ISSUE TITLE
ERROR:  operator class "vector_cos_ops" does not exist for access method "vectors"

### ISSUE THREAD

**Issue by fyfrey** [tensorchord/pgvecto.rs#385]
I'm using version 0.2.0 on postgres15 (Debian bookworm ARM64 installed via .deb file) and see the error

`ERROR:  operator class "vector_cos_ops" does not exist for access method "vectors"`

when trying to add an index after `SET vectors.pgvector_compatibility=on;` with

```
      CREATE INDEX IF NOT EXISTS indexname ON tablename
      USING hnsw (embedding vector_cosine_ops)
      WITH (ef_construction = 300, m = 16);
```

Datatype of `embedding` is `vector(512)`.

The database had an extension installation of version 0.1.11 before. But I removed that with DROP EXTENSION, reset shared library path, restarted and had a postgres database without pgvecto.rs extension. Then, I followed the install instructions for 0.2.0

Any pointers?

**Comment by cutecutecat** [comment]
Hello, I think this may be related to some error at: 
https://github.com/tensorchord/pgvecto.rs/blob/8aa621a4bfa484d1acb952ac4d0bbcbc84ad408e/src/index/compat.rs#L18

Could you please show your logs after `logging_collector=on`:

There might be some warnings containing `will not be overwritten`.

The log might be at `/var/lib/postgresql/15/main/log/postgresql-2024-01-11_094502.log` or `/var/log/postgresql/postgresql-15-main.log`, when logging_collector is on or off, if you installed by `deb` at local machine.

**Comment by cutecutecat** [comment]
There might be some errors at schema installing.
Could you please run:
```sql
SELECT am.amname AS index_method,
       opc.opcname AS opclass_name,
       opc.opcintype::regtype AS indexed_type,
       opc.opcdefault AS is_default
    FROM pg_am am, pg_opclass opc
    WHERE opc.opcmethod = am.oid AND am.amname = 'vectors' 
    ORDER BY index_method, opclass_name;
```
and show the result.

**Comment by VoVAllen** [comment]
This is possibly related to the search path problem. Can you show the result of `SHOW search_path;`?

Ref: https://github.com/tensorchord/pgvecto.rs/issues/383

**Comment by fyfrey** [comment]
@cutecutecat Thanks for the quick response! The result looks different:
```
 index_method |  opclass_name  |  indexed_type  | is_default 
--------------+----------------+----------------+------------
 vectors      | vecf16_cos_ops | vectors.vecf16 | f
 vectors      | vecf16_dot_ops | vectors.vecf16 | f
 vectors      | vecf16_l2_ops  | vectors.vecf16 | f
 vectors      | vector_cos_ops | vectors.vector | f
 vectors      | vector_dot_ops | vectors.vector | f
 vectors      | vector_l2_ops  | vectors.vector | f
```

How can i fix this?


@VoVAllen result of `SHOW search_path;` is
```
 "$user", public, vectors
```

**Comment by cutecutecat** [comment]
> The result looks different

Based on postgres [doc](https://www.postgresql.org/docs/9.5/datatype-oid.html):

> All of the OID alias types for objects grouped by namespace accept schema-qualified names, and will display schema-qualified names on output if the object would not be found in the current search path without being qualified.

The displayed `vectors.vector` usually means `search_path` is not set/correct, but as you shows it has been set, so it might be strange, need a deeper survey.

**Comment by fyfrey** [comment]
Thanks for your time and help. I was finally able to figure it out:
The vectors schema was owned by the postgres default user. The database in question (and debug commands run for this issue) is accessed by another user. Changing the owner of the vectors schema to my application user resolved the issues.

For my future self or other with the same issue:
`ALTER SCHEMA vectors OWNER TO yourUserName`.
