### ISSUE TITLE
pgvecto.rs 0.2.1 much slower than pgvector 0.6.1?

### ISSUE THREAD

**Issue by ergo70** [tensorchord/pgvecto.rs#418]
Hello,

I did a simple benchmark of pgvecto.rs 0.2.1 vs. pgvector 0.6.1 on PostgreSQL 16.2. And pgvecto.rs seems to be **much** slower? PostgreSQL and pgvector were compiled from source, pgvecto.rs installed as binary Release on Ubuntu 22.04.3 LTS on WSL2 / Windows 11. The dataset used is dbpedia-openai-1M-1536-angular.

Baseline:
```

             Table "public.items_plain"
  Column   |  Type   | Collation | Nullable | Default
-----------+---------+-----------+----------+---------
 id        | integer |           |          |
 embedding | text    |           |          |


postgres=# select count(*) from items_plain;
 count
--------
 975000
(1 row)
```
pgvector:
```
postgres=# create extension vector;
CREATE EXTENSION

postgres=# CREATE TABLE items (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                embedding vector(1536) NOT NULL
            );
CREATE TABLE

postgres=# \timing
Timing is on.

insert into items (id, embedding) select id, embedding::vector from items_plain;
INSERT 0 975000
Time: 238332.482 ms (03:58.332)

postgres=# set maintenance_work_mem to '7GB';
SET
Time: 0.280 ms

postgres=# CREATE INDEX on items USING hnsw(embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128);
CREATE INDEX
Time: 414950.296 ms (06:54.950)

postgres=# reset maintenance_work_mem;
RESET
Time: 29.158 ms

postgres=# vacuum (analyze, freeze) items;
VACUUM
Time: 1506.544 ms (00:01.507)

postgres=# explain analyze SELECT id, embedding <=> (select embedding from items where id=1) AS _score FROM items ORDER BY _score LIMIT 100;
                                                                   QUERY PLAN

------------------------------------------------------------------------------------------------------------
------------------------------------
 Limit  (cost=12406.35..12408.36 rows=100 width=12) (actual time=19.114..21.987 rows=40 loops=1)
   InitPlan 1 (returns $1)
     ->  Gather  (cost=1000.00..12289.23 rows=1 width=18) (actual time=0.128..19.966 rows=1 loops=1)
           Workers Planned: 2
           Workers Launched: 2
           ->  Parallel Seq Scan on items items_1  (cost=0.00..11289.12 rows=1 width=18) (actual time=10.029
..15.763 rows=0 loops=3)
                 Filter: (id = 1)
                 Rows Removed by Filter: 325000
   ->  Index Scan using items_embedding_idx on items  (cost=117.12..19757.82 rows=975000 width=12) (actual t
ime=19.112..19.454 rows=40 loops=1)
         Order By: (embedding <=> $1)
 Planning Time: 0.397 ms
 **Execution Time: 22.044 ms**
(12 rows)

Time: 31.540 ms
```
pgvecto.rs:
```
postgres=# create extension vectors;
CREATE EXTENSION

postgres=# CREATE TABLE items (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                embedding vector(1536) NOT NULL
            );
CREATE TABLE

postgres=# insert into items (id, embedding) select id, embedding::vector from items_plain;
INSERT 0 975000
Time: 244108.059 ms (04:04.108)

postgres=# set maintenance_work_mem to '7GB';
SET
Time: 0.118 ms

postgres=# CREATE INDEX on items USING vectors (embedding vector_cos_ops) WITH (options = $$
[indexing.hnsw]
$$);
CREATE INDEX
Time: 30634.369 ms (00:30.634)

postgres=# reset maintenance_work_mem;
RESET
Time: 5.618 ms

postgres=# vacuum (analyze, freeze) items;
VACUUM
Time: 1665.551 ms (00:01.666)

postgres=# explain analyze SELECT id, embedding <=> (select embedding from items where id=1) AS _score FROM items ORDER BY _score LIMIT 100;
                                                                   QUERY PLAN

------------------------------------------------------------------------------------------------------------
------------------------------------
 Limit  (cost=12289.23..12291.11 rows=100 width=8) (actual time=591.116..592.970 rows=100 loops=1)
   InitPlan 1 (returns $1)
     ->  Gather  (cost=1000.00..12289.23 rows=1 width=18) (actual time=0.151..18.768 rows=1 loops=1)
           Workers Planned: 2
           Workers Launched: 2
           ->  Parallel Seq Scan on items items_1  (cost=0.00..11289.12 rows=1 width=18) (actual time=10.568
..16.715 rows=0 loops=3)
                 Filter: (id = 1)
                 Rows Removed by Filter: 325000
   ->  Index Scan using items_embedding_idx on items  (cost=0.00..18398.70 rows=975000 width=8) (actual time
=591.114..592.884 rows=100 loops=1)
         Order By: (embedding <=> $1)
 Planning Time: 0.077 ms
 **Execution Time: 593.042 ms**
(12 rows)

Time: 593.463 ms
```
pgvecto.rs is about 27x slower than pgvector with fp32 vectors? That somewhat contradicts your benchmarks, so I might be doing something wrong. Or it is something else.

best regards,

Ernst-Georg

**Comment by usamoi** [comment]
> `pgvecto.rs` constructs the index asynchronously. When you insert new rows into the table, they will first be placed in an append-only file. The background thread will periodically merge the newly inserted row to the existing index. When a user performs any search prior to the merge process, it scans the append-only file to ensure accuracy and consistency.

You need to check the view `pg_vector_index_stat` to monitor the progress of indexing.

https://docs.pgvecto.rs/usage/monitoring.html

**Comment by VoVAllen** [comment]
Here's the code we used in benchmark to check the build status: https://github.com/silver-ymz/vector-db-benchmark/blob/30164378f2c8bb06d30d89de3bc96c836da1b2fd/engine/clients/pgvector/upload.py#L91-L95

**Comment by ergo70** [comment]
Thank you for the info. IMHO, this is pretty unusual behavior for PostgreSQL, having an INDEX that still can mutate in the background **after** CREATE INDEX has reported completion. I have never seen PostgreSQL or any extension behave like this, up to now. But obviously I have not seen them all. ;-)

Does this mutability is guarentted to never cross transaction boundaries, i.e. can any individual transaction rely on the current state of the INDEX it saw when it was started? Otherwise, one transaction could change the content of the INDEX independent of the data versions visible in another transaction, e.g. by DELETE.

But anyway, judging from the documentation and the code, I should check if idx_status is NORMAL, and idx_indexing is true in pg_vector_index_stat? (The code points to  cur.execute("SELECT idx_indexing FROM pg_vector_index_info;") but pg_vector_index_info does not exist. I assume this is pg_vector_index_stat now).

```
postgres=# SELECT idx_status, idx_indexing FROM pg_vector_index_stat;
 idx_status | idx_indexing
------------+--------------
 NORMAL     | t
(1 row)
```

And...

```
postgres=# explain analyze SELECT id, embedding <=> (select embedding from items where id=1) AS _score FROM items ORDER BY _score LIMIT 100;
                                                                   QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=12289.23..12291.11 rows=100 width=8) (actual time=567.031..570.355 rows=100 loops=1)
   InitPlan 1 (returns $1)
     ->  Gather  (cost=1000.00..12289.23 rows=1 width=18) (actual time=0.154..19.708 rows=1 loops=1)
           Workers Planned: 2
           Workers Launched: 2
           ->  Parallel Seq Scan on items items_1  (cost=0.00..11289.12 rows=1 width=18) (actual time=11.191..17.660 rows=0 loops=3)
                 Filter: (id = 1)
                 Rows Removed by Filter: 325000
   ->  Index Scan using items_embedding_idx on items  (cost=0.00..18398.70 rows=975000 width=8) (actual time=567.029..570.282 rows=100 loops=1)
         Order By: (embedding <=> $1)
 Planning Time: 0.078 ms
 Execution Time: 570.502 ms
(12 rows)
```

No change to my previous result.

best regards

Ernst-Georg

**Comment by gaocegege** [comment]
```diff
postgres=# SELECT idx_status, idx_indexing FROM pg_vector_index_stat;
 idx_status | idx_indexing
------------+--------------
- NORMAL     | t
+ NORMAL     | f
(1 row)
```

It should be `idx_indexing=false`, indicating that the indexing is complete.

**Comment by VoVAllen** [comment]
This behavior is similar to the fast_update parameters of the GIN index.

**Comment by ergo70** [comment]
"This behavior is similar to the fast_update parameters of the GIN index."

Not quite. It is correct that the fastupdate mechanism uses a list of pending changes:

1. They are not applied asynchronously, except by auto VACUUM. A GIN update hitting gin_pending_list_limit, or triggered by gin_clean_pending_list() will run synchronously
2. It is configurable via pending_list_limit and fastupdate for controlling latency

https://www.postgresql.org/docs/current/gin-implementation.html

While this might sound like nitpicking, GIN behavior is documented and user controllable, which is important if you run PostgreSQL in production.

But what concerns me more is this:

"But there is an additional requirement for any table scan in PostgreSQL: it must verify that each retrieved row be “visible” to the query's MVCC snapshot, as discussed in [Chapter 13](https://www.postgresql.org/docs/current/mvcc.html). Visibility information is not stored in index entries, only in heap entries; so at first glance it would seem that every row retrieval would require a heap access anyway. And this is indeed the case, if the table row has been modified recently."

https://www.postgresql.org/docs/current/indexes-index-only-scans.html

Does your mechanism properly consult the visibility map when updating the index asynchronously? Otherwise this would introduce dirty reads, which PostgreSQL does not support: https://www.postgresql.org/docs/current/transaction-iso.html

If the indexing time is quite long, PostgreSQL has CREATE INDEX CONCURRENTLY, which is well established since v8.2: https://www.postgresql.org/docs/16/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY, and integrates well with the rest of PostgreSQL's machinery.

One key promise and strength of PostgreSQL is guaranteed data consistency and IMHO this must not be compromised. That's why I'm asking all those questions.

best regards

Ernst-Georg

**Comment by usamoi** [comment]
> Does your mechanism properly consult the visibility map when updating the index asynchronously?

The visibility map is consulted in queries and not handled by indexes.

> If the indexing time is quite long, PostgreSQL has CREATE INDEX CONCURRENTLY

`pgvecto.rs` supports it.

> One key promise and strength of PostgreSQL is guaranteed data consistency and IMHO this must not be compromised.

I agree with you.

**Comment by ergo70** [comment]
```
postgres=# SELECT idx_status, idx_indexing FROM pg_vector_index_stat;
 idx_status | idx_indexing
------------+--------------
 NORMAL     | f
(1 row)

postgres=# explain analyze SELECT id, embedding <=> (select embedding from items where id=1) AS _score FROM items ORDER BY _score LIMIT 100;
                                                                  QUERY PLAN

------------------------------------------------------------------------------------------------------------
----------------------------------
 Limit  (cost=12289.23..12291.11 rows=100 width=8) (actual time=14.484..16.928 rows=100 loops=1)
   InitPlan 1 (returns $1)
     ->  Gather  (cost=1000.00..12289.23 rows=1 width=18) (actual time=0.132..13.139 rows=1 loops=1)
           Workers Planned: 2
           Workers Launched: 2
           ->  Parallel Seq Scan on items items_1  (cost=0.00..11289.12 rows=1 width=18) (actual time=7.382.
.11.660 rows=0 loops=3)
                 Filter: (id = 1)
                 Rows Removed by Filter: 325000
   ->  Index Scan using items_embedding_idx on items  (cost=0.00..18398.70 rows=975000 width=8) (actual time
=14.482..16.881 rows=100 loops=1)
         Order By: (embedding <=> $1)
 Planning Time: 0.074 ms
 Execution Time: 16.987 ms
(12 rows)
```

This looks better now. ;-)
