### ISSUE TITLE
test: Test pgvecto.rs FDW against postgres with pgvector

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#421]
Check whether pgvecto.rs can be connected to AWS RDS/supabase (postgres without pgvecto.rs) through FDW.

**Comment by gaocegege** [comment]
Ref #354

**Comment by gaocegege** [comment]
Could you please illustrate more about the issue? e.g. How to check it.

**Comment by VoVAllen** [comment]
Start one postgres with pgvector, and check whether it can use FDW to connect to pgvecto.rs instance. Need to check whether create index/select/insert operation works. 

And finally to check the performance on AWS RDS/supabase, and run some real world workload to check whether everything works as expected.
