### ISSUE TITLE
vector type not found in the database - pgvecto_rs.psycopg register_vector

### ISSUE THREAD

**Issue by alfer-edb** [tensorchord/pgvecto.rs#449]
Hi all, 

I'm trying to set up a python script where I make use of pgvecto-rs python bindings module following this [example](https://github.com/tensorchord/pgvecto.rs/blob/main/bindings/python/examples/psycopg_example.py).

I installed pgvecto.rs extension and py module successfully, made sure `vectors` was in `search_path`, created the extension, adedd to `shared_preload_libraries` and manually created a table using the `vector` datatype, so apparently all looks good. 

Hoewever, when i invoke the function `register_vector` I get the following error:

>  ProgrammingError(info="vector type not found in the database")

Here my piece of code:
```

import sys
import os
import numpy as np

from pgvecto_rs.psycopg import register_vector
import psycopg

url = "postgresql://{username}:{password}@{host}:{port}/{db_name}".format(
            port=os.getenv("DB_PORT", "5432"),
            host=os.getenv("DB_HOST", "localhost"),
            username=os.getenv("DB_USER", "ann1"),
            password=os.getenv("DB_PASS", "ann1"),
            db_name=os.getenv("DB_NAME", "ann1")
        )
        with psycopg.connect(url) as conn:
            conn.execute("CREATE EXTENSION IF NOT EXISTS vectors;")
            register_vector(conn)
            conn.execute("CREATE TABLE items (id int, embedding vector(3))" )
```

I was able to catch the query invoked by `register_vector` that is returning the error, which is:

```
SELECT
	    typname AS name, oid, typarray AS array_oid,
	    oid::regtype::text AS regtype, typdelim AS delimiter
	FROM pg_type t
	WHERE t.oid = to_regtype($1)
	ORDER BY t.oid`

DETAIL:  parameters: $1 = 'vector'
```

Running that query on the database, I do see the `vector` type:

```
ann1=# SELECT
            typname AS name, oid, typarray AS array_oid,
            oid::regtype::text AS regtype, typdelim AS delimiter
        FROM pg_type t
        WHERE t.oid = to_regtype('vector')
        ORDER BY t.oid;
  name  |  oid  | array_oid | regtype | delimiter
--------+-------+-----------+---------+-----------
 vector | 24755 |     24793 | vector  | ,

```

I really can't see why I get that error, any ideas? 
Thanks!

**Comment by alfer-edb** [comment]
UPDATE:

I found something odd, if I run the query above as postgres user i get:

```
ann1=# SELECT
            typname AS name, oid, typarray AS array_oid,
            oid::regtype::text AS regtype, typdelim AS delimiter
        FROM pg_type t
        WHERE t.oid = to_regtype('vector')
        ORDER BY t.oid;
  name  |  oid  | array_oid | regtype | delimiter
--------+-------+-----------+---------+-----------
 vector | 24755 |     24793 | vector  | ,
```

While as ann1 user:

```
ann1=> SELECT
            typname AS name, oid, typarray AS array_oid,
            oid::regtype::text AS regtype, typdelim AS delimiter
        FROM pg_type t
        WHERE t.oid = to_regtype('vector')
        ORDER BY t.oid;
 name | oid | array_oid | regtype | delimiter
------+-----+-----------+---------+-----------
(0 rows)
```

However, if I replace the function `to_regtype('vector')` with oid 24755 I get: 

```
ann1=> SELECT
            typname AS name, oid, typarray AS array_oid,
            oid::regtype::text AS regtype, typdelim AS delimiter
        FROM pg_type t
        WHERE t.oid = 24755
        ORDER BY t.oid;
  name  |  oid  | array_oid |    regtype     | delimiter
--------+-------+-----------+----------------+-----------
 vector | 24755 |     24793 | vectors.vector | ,
(1 row)
```

For some reasons the function `to_regtype` is returning null. The user ann1 has been granted all privileges.

**Comment by VoVAllen** [comment]
Looks like some kind of permission issue. Have you tried grant permission to the user for the vectors schema and change the search path to include the  schema?

**Comment by cutecutecat** [comment]
Can you show me the result of:
```sql
SHOW search_path;
```
And try this:
```sql
SET search_path = "$user", public, vectors';
``` 
in your session?

**Comment by alfer-edb** [comment]
@VoVAllen I checked and in fact my non-privileged user did not have permissions to use the extension. I just ran `GRANT ALL ON SCHEMA vectors to ann1`  as postgres user and the issue is solved :)

Closing the issue, thank you everyone.
