### ISSUE TITLE
How to find index size ?

### ISSUE THREAD

**Issue by alfer-edb** [tensorchord/pgvecto.rs#454]
Hi all, 

It might be a silly question and I apologize in advance,  but I'm having hard time figuring out the size of an index using pgvecto.rs
An example after I loaded 1000000 rows with 128 dimensions:

```
CREATE INDEX items_embedding_idx ON items USING vectors (embedding vector_l2_ops) WITH (options = $$ [indexing.hnsw]
	 m = 16
	 ef_construction = 80 $$)

ann1=# select * from pg_stat_all_indexes where indexrelname='items_embedding_idx';

-[ RECORD 1 ]-+--------------------
relid         | 16918
indexrelid    | 16923
schemaname    | public
relname       | items
indexrelname  | items_embedding_idx
idx_scan      | 0
last_idx_scan |
idx_tup_read  | 910
idx_tup_fetch | 910

ann1=# SELECT pg_relation_size('items_embedding_idx');
-[ RECORD 1 ]----+--
pg_relation_size | 0
```

The above shows 0 bytes for the index `items_embedding_idx` but stats are showing the index is being used. 
I discovered the view `pg_vector_index_stat` which seems the right place to find the info I'm looking for:

```
ann1=# select * from pg_vector_index_stat ;

-[ RECORD 1 ]+
tablerelid   | 16918
indexrelid   | 16923
tablename    | items
indexname    | items_embedding_idx
idx_status   | NORMAL
idx_indexing | f
idx_tuples   | 1000000
idx_sealed   | {1000000}
idx_growing  | {}
idx_write    | 0
idx_size     | 690648136
idx_options  | {"vector":{"dimensions":128,"distance":"L2","kind":"F32"},"segment":{"max_growing_segment_size":20000,"max_sealed_segment_size":1000000},"optimizing":{"sealing_secs":60,"sealing_size":1,"optimizing_threads":8},"indexing":{"hnsw":{"m":16,"ef_construction":80,"quantization":{"trivial":{}}}}}

```

Is the index size expressed in bytes? Is the index not showing under `pg_stat_all_indexes` expected?

Thanks

**Comment by alfer-edb** [comment]
Also, I see pgvecto.rs constructs the index asynchronously but is there a way to force the index to be built synchronously ? Or a way to calculate the final index size before starting queries ?

**Comment by mertalev** [comment]
I think making `CREATE INDEX` synchronous is planned in #436. In the meantime, you can periodically query `pg_vector_index_stat` until `idx_indexing` is false.

**Comment by gaocegege** [comment]
Hello, I'm curious to know if there has been any progress made so far. Additionally, please let me know if there is any other assistance you require.

@alfer-edb
