### ISSUE TITLE
feat: ANN benchmark

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#460]
Contribute to https://ann-benchmarks.com/

**Comment by kemingy** [comment]
- Check the PR: https://github.com/erikbern/ann-benchmarks/pull/510

**Comment by gaocegege** [comment]
pgvector, and pgvecto.rs

**Comment by gaocegege** [comment]
Some ANN benchmarks results

![image](https://github.com/tensorchord/pgvecto.rs/assets/5100735/4aaf6858-dcc7-4622-8efb-c617387f5942)

![image](https://github.com/tensorchord/pgvecto.rs/assets/5100735/ced48ec4-cf1c-45d8-b1b4-140621235fd2)

We tested ANN benchmarks and got some initial results. However, we don't believe that it reflects the real-world workloads. For example, it only uses one process to send query requests, which doesn't take concurrency into consideration. Our design includes an IPC for each request, which affects the results. If we send requests using multiple processes at the same time, the database's observed speed (QPS) is much higher than pgvector.
