### ISSUE TITLE
feat: Roadmap

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#5]
Feature:
- Vectorize distance operations
- Custom Index using IVF
- Custom index using HNSW
- Custom index using ScaNN
- Support Vec8, Vec16

Tests:
- Add benchmarks
- Add unit tests

Reference 
- https://github.com/pgvector/pgvector
- ​https://github.com/postgres/postgres/tree/master/contrib/bloom

**Comment by gaocegege** [comment]
Maybe we could use https://github.com/qdrant/vector-db-benchmark to benchmark it

**Comment by karajan1001** [comment]
I suggest creating separate tickets for each new feature. And if someone is working on one of the features, he can assign it to himself. I'm interested in it but do not know the current condition of each feature.

**Comment by gaocegege** [comment]
@karajan1001 We already created separate issues. Thanks for the advice.
