### ISSUE TITLE
feat(SDK): Django ORM support

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/pgvecto.rs#518]
From ozu.ai's request

Ref https://docs.djangoproject.com/en/5.0/topics/db/queries/

Similar to https://github.com/pgvector/pgvector-python?tab=readme-ov-file#django

**Comment by zbloss** [comment]
This would be great to add

**Comment by gaocegege** [comment]
The PR is ready to merge. https://github.com/tensorchord/pgvecto.rs-py/pull/7
