### ISSUE TITLE
Postgres vector extension comparison table

### ISSUE THREAD

**Issue by ClearedFram3** [tensorchord/pgvecto.rs#59]
Y'all have done some awesome work—thank you!

I would like to ask for a table or section comparing pgvector, pg_embedded, and pgvecto.rs. It would be really helpful, especially for those new to the subject.

**Comment by VoVAllen** [comment]
Thanks for your interest! I'm actually writing a blog comparing pgvecto.rs and pgvector. Here're some briefs and we hope we can finish the whole blog before Friday this week. 

![image](https://github.com/tensorchord/pgvecto.rs/assets/8686776/b5c04567-0b79-4a4b-86cb-65315f9e9857)

![299de17f-edaa-43af-8353-c6d0785b643f](https://github.com/tensorchord/pgvecto.rs/assets/8686776/84c359b1-e3ce-4c6b-81c9-59d97f86d657)

**Comment by gaocegege** [comment]
Thanks for raising this! I think we could have a section in readme for this.

**Comment by ClearedFram3** [comment]
@VoVAllen where you able to write that article? Really interested in reading it!

**Comment by VoVAllen** [comment]
@ClearedFram3 https://github.com/tensorchord/pgvecto.rs/blob/main/docs/comparison-pgvector.md

**Comment by ClearedFram3** [comment]
Perfect, thanks!!
