### ISSUE TITLE
reason=pgvecto.rs: IPC connection is closed unexpectedly for 100M dataset 

### ISSUE THREAD

**Issue by agandra30** [tensorchord/pgvecto.rs#592]
Hi folks,

I am trying to validate and see if we could leverage pgvector.rs for our usecases at scale.
Tried to create an HNSW MetricType.L2: 'L2' and parameters looks like this : 
```
create_index_after_load=True
max_parallel_workers=16 
quantization_type='trivial' 
index=<IndexType.HNSW: 'HNSW'> 
m=16 ef_search=100 
ef_construction=300  index for the 100M using HNSW 
```
I ran 3 times and it failed 

`dataset': {'data': {'name': 'LAION', 'size': 100000000, 'dim': 768, 'metric_type': <MetricType.L2: 'L2'>}}, 'db': 'PgVectoRS-100mHNSWpgvectorrsr1v1-100mHNSWpgvectorrsr1v1'} failed to run, reason=pgvecto.rs: IPC connection is closed unexpectedly.`

NOTE:  The DB is up and the table is present  it it a problem with the plugin ? or shall we switch back to the older pgvector plugin instead of rs ?  any recommendations ?

`You are now connected to database "mydatabase" as user "postgres" 
mydatabase=# \dx;
                                                 List of installed extensions
  Name   | Version |   Schema   |                                         Description                                          
---------+---------+------------+----------------------------------------------------------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 vectors | 0.0.0   | vectors    | vectors: Vector database plugin for Postgres, written in Rust, specifically designed for LLM`

**Comment by VoVAllen** [comment]
It's possible with 100M vectors, but you will need 1.5x-2x memory comparing to the total vector size

**Comment by agandra30** [comment]
@VoVAllen  thanks for the reply when you say memory  , Because in my setup the postgres is running on a machine that have close to 1Ti of Memory  Also are there any postgres settings that you recommend ?

1.  Since pgvector.rs is failing , do you recommend pgvector the old C based extension  instead of this ?
2.  Its a single node configuration any tunabels you recommend 

`# free  -mh
               total        used        free      shared  buff/cache   available
Mem:           1.0Ti        12Gi       598Gi       152Mi       396Gi       989Gi
Swap:             0B          0B          0B`

**Comment by agandra30** [comment]
@VoVAllen  I saw there is a fix given for this in 0.2.0 so i have even  tried the executions with the latest release 0.3.0 . Still same issue 

![image](https://github.com/user-attachments/assets/ca34d6f2-c583-4e5b-b2e7-21dd64f14994)

**Comment by cutecutecat** [comment]
Hello, I am the author of `PGVecto.rs` backend of https://github.com/zilliztech/VectorDBBench.

Large dataset like `cohere-10M`, `openai-5M` and `laion-100M` are not yet been validated on PGVecto.rs before.

We are invesigating the result of them on AWS now:
-  `cohere-10M` on `32c`: QPS=11228 recall=0.8526 max_memory_usage=39525MB build_time=21812s
- `laion-100M` on `64c`: In progress

Based on current observations, `laion-100M` would cost not less than 329834 MB, about 512GB memory is enough.

We will continue to pay attention to the bench results, and let you know if we have some conclusions.

**Comment by cutecutecat** [comment]
Sorry about the delay. We haven't finish the `laion-100M` dataset test as the AWS instance is too expensive. Nevertheless, It seems to be fine at about first 50%-67% preocess of index build procedure, without any error. The image we pick for test is `tensorchord/pgvecto-rs:pg16-v0.4.0-alpha.2`.

As there is many bugfix before `0.4.0`, it's hard to identify the key issue. We recommend you could use the above image to rerun the test, and check whether the error happens.

For `PGVecto.rs 0.4.0`, there is a few changed at `VectorDBBench`, you could manually upgrade the dependency of SDK to `0.2.2` or wait https://github.com/zilliztech/VectorDBBench/pull/373 to be merged.

I will close this comment after the VectorDBBench PR is finished. If you have any update, feel free to let me know.
