### ISSUE TITLE
Release assets for PostgreSQL 17 / Next pgvecto.rs release date

### ISSUE THREAD

**Issue by jeroenhabets** [tensorchord/pgvecto.rs#607]
After learning about your project I've been rather keen to start using it myself.

With PostgreSQL 17 released almost a month ago (2024-09-26) I'd like to (finally) be able to use it for a new project (in order to save one major PostgreSQL upgrade later).

Therefore for me it would be great to also have .deb (and I guess for others .zip) packages for vectors-pg17.

E.g. pg17 instead of pg16 in the next set like below for 0.4.0-alpha:
vectors-pg16_0.4.0-alpha.2_amd64.deb
vectors-pg16_0.4.0-alpha.2_arm64.deb
vectors-pg16_aarch64-unknown-linux-gnu_0.4.0-alpha.2.zip
vectors-pg16_x86_64-unknown-linux-gnu_0.4.0-alpha.2.zip 

NOTE: I'm not sure if PR #600 already covers this or not so I thought I'd ask. Also any idea when you will release a next version of pgvecto.rs?

**Comment by cutecutecat** [comment]
Thank you for your attention. We have released v0.4.0 with PostgreSQL 17 support. PGVecto.rs is now stable. This will be the last release with feature updates, future releases will only contain urgent bug fixes.

If you encounter any problems while using it, feel free to open a new issue.

**Comment by graveland** [comment]
I'd like to start testing with this, when will the release and binary assets be available?

**Comment by geraldwuhoo** [comment]
There was definitely a release when I checked yesterday. Seems like it was taken down for whatever reason.

**Comment by VoVAllen** [comment]
We're preparing the upgrade SQL which is missing in today's release. https://github.com/tensorchord/pgvecto.rs/pull/615

Will try to finish this tomorrow. cc @geraldwuhoo @graveland @xXentaOps
