### ISSUE TITLE
Indexing does not finishes (v0.4.0-alpha.2)

### ISSUE THREAD

**Issue by javiabellan** [tensorchord/pgvecto.rs#618]
Hi,

Sorry if this is a dumb question but i have executed an indexing process and I don't know how is it going (some percentage or something) or even if is it dead or blocked (and how to safely stop it, if is that the case).

Here is the context:

- pgvecto.rs version: v0.4.0-alpha.2
- Data: Table with vecf16(768) not null column populated with ~6 million vectors 
- Indexing command:
```sql
CREATE INDEX idx_images_hnsw ON images
USING vectors (img_emb vecf16_dot_ops)
WITH (options='[indexing.hnsw]
m = 32
ef_construction = 300');
```

I have run this command in a interactive psql terminal inside TMUX and it does not return (more than 8 hours)

Here is the output of `SELECT * FROM pg_stat_activity;` associated row:
```json
{
	"datid": 16389,
	"datname": "my_database",
	"pid": 2514101,
	"leader_pid": null,
	"usesysid": 10,
	"usename": "postgres",
	"application_name": "psql",
	"client_addr": null,
	"client_hostname": null,
	"client_port": -1,
	"backend_start": "2024-11-23 18:22:30.007315+00",
	"xact_start": "2024-11-23 18:26:20.395945+00",
	"query_start": "2024-11-23 18:26:20.395945+00",
	"state_change": "2024-11-23 18:26:20.395948+00",
	"wait_event_type": "Timeout",
	"wait_event": "PgSleep",
	"state": "active",
	"backend_xid": "37025",
	"backend_xmin": "37025",
	"query_id": null,
	"query": "CREATE INDEX idx_images_hnsw ON images\nUSING vectors (img_emb vecf16_dot_ops)\nWITH (options='[indexing.hnsw]\nm = 32\nef_construction = 300\n');",
	"backend_type": "client backend"
}
```

Here is the output of `SELECT * FROM pg_stat_progress_create_index;` associated row:

```json
{
	"pid": 2514101,
	"datid": 16389,
	"datname": "my_database",
	"relid": 769639,
	"index_relid": 0,
	"command": "CREATE INDEX",
	"phase": "building index",
	"lockers_total": 0,
	"lockers_done": 0,
	"current_locker_pid": 0,
	"blocks_total": 955267,
	"blocks_done": 955267,
	"tuples_total": 0,
	"tuples_done": 0,
	"partitions_total": 0,
	"partitions_done": 0
}
```

and finally `SELECT * FROM pg_vector_index_stat;` does return nothing.

I dont know if i am missing something. Or is a v0.4.0-alpha.2 bug. Also what is the recommended steps to upgrade to v0.4.0 stable version ? Because this was my installation process:

```bash
wget https://github.com/tensorchord/pgvecto.rs/releases/download/v0.4.0-alpha.2/vectors-pg16_x86_64-unknown-linux-gnu_0.4.0-alpha.2.zip -O vectors.zip
unzip vectors.zip -d vectors                                    # Unzip download
cp vectors/vectors.so $(pg_config --pkglibdir)/                 # Copy library to `$pkglibdir`
cp vectors/vectors--* $(pg_config --sharedir)/extension/        # Copy schema to `$shardir`
cp vectors/vectors.control $(pg_config --sharedir)/extension/   # Copy schema to `$shardir`
rm -rf vectors vectors.zip                                      # Delete download
```

## Update

Reading https://lantern.dev/blog/hnsw-index-creation i've realised that maybe was a hardware resource problem

#### RAM:
```sql
show work_mem; -- i have 64MB. They recommend 2GB
show maintenance_work_mem; --  i have 64MB. They recommend 5GB
show shared_buffers; -- i have 128MB. They recommend 12GB
```

#### CPU cores:

Is this syntax correct ?
```sql
CREATE INDEX idx_images_hnsw ON images
USING vectors (img_emb vecf16_dot_ops)
WITH (options='[indexing.hnsw]
m = 32
ef_construction = 300
optimizing.optimizing_threads = 32
');
```

And is it save to stop (crtl-C) the indexing, to repeat it with more hardware resources ?

**Comment by cutecutecat** [comment]
## Unfinish index build

Hello, I think it is not dead, by default the index build procedure will use only **1** thread, and it is defenitly very slow.
The most important thing is to use multi-threads.

Therefore, your fix is absolutely correct, it is okay to have such a:
```
CREATE INDEX idx_images_hnsw ON images
USING vectors (img_emb vecf16_dot_ops)
WITH (options='[indexing.hnsw]
m = 32
ef_construction = 300
optimizing.optimizing_threads = 32
');
```

We recommend to use 32 threads if you have a CPU of 16 / 32 / more cores.

## Other issues

> upgrade to v0.4.0 stable version

I could share you a script to upgrade, but it is **not under tested**. 
Be careful to use it, and feel free to let me know if there is any issue at update.
```
# stop postgreSQL
sudo systemctl stop postgresql.service

# drop old extension
sudo rm -rf $(pg_config --pkglibdir)/vectors.so
sudo rm -rf $(pg_config --pkglibdir)/vectors--
sudo rm -rf $(pg_config --sharedir)/extension/vectors.control

# install new ones
wget https://github.com/tensorchord/pgvecto.rs/releases/download/v0.4.0/vectors-pg16_x86_64-unknown-linux-gnu_0.4.0.zip -O vectors.zip
unzip vectors.zip -d vectors                                    # Unzip download
cp vectors/vectors.so $(pg_config --pkglibdir)/                 # Copy library to `$pkglibdir`
cp vectors/vectors--* $(pg_config --sharedir)/extension/        # Copy schema to `$shardir`
cp vectors/vectors.control $(pg_config --sharedir)/extension/   # Copy schema to `$shardir`
rm -rf vectors vectors.zip

# restart postgreSQL
sudo systemctl start postgresql.service

# upgrade: psql -h 127.0.0.1 ...
## Any index should be dropped when update to v0.4.0
DROP index xxx;
ALTER extension vectors update;
```

If it fails, you can revert by switch back to `v0.4.0-alpha.2` and rerun the script.

> And is it safe to stop (crtl-C) the indexing, to repeat it with more hardware resources ?

It can be said to be safe, but you will have to wait some time for the index build to finish gracefully, it could be as long as tens of minutes.

We observe that sometimes it might still be stuck for a long time when pressing `ctrl+c`. If you encounter this, restarting PostgreSQL and dropping the index might be a solution.

**Comment by javiabellan** [comment]
Thank you very much, you were right, the index was not dead it just took 1day and 8 hours to build. Thanks also for the upgrade to v0.4.0 script.
