### ISSUE TITLE
feat: Quantization Index support

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#68]
Faiss supports lots of quantization options
such as https://faiss.ai/cpp_api/struct/structfaiss_1_1IndexHNSWPQ.html
- HNSWPQ
- HNSWSQ
- HNSW2Level
- IVFPQ/IVFSQ

And for the quantization levels, there're
- SQ4/SQ8/SQfp16
- PQ64/PQ16
- OPQ32/OPQ16

Reference: 
- https://github.com/facebookresearch/faiss/wiki/Vector-codec-benchmarks
- https://github.com/finalfusion/reductive
- https://github.com/qdrant/quantization

**Comment by VoVAllen** [comment]
@usamoi is currently working on IVFPQ

**Comment by gaocegege** [comment]
Is there any progress?

**Comment by VoVAllen** [comment]
@gaocegege Already implemented in https://github.com/tensorchord/pgvecto.rs/pull/81

**Comment by gaocegege** [comment]
Then let's close this?

**Comment by VoVAllen** [comment]
Finished product and scalar quantization for both IVF and HNSW
