### ISSUE TITLE
consider buying pgvecto.rs domain name

### ISSUE THREAD

**Issue by dataf3l** [tensorchord/pgvecto.rs#85]
it appears to be available as of 2023 sept 29

➜  ~ whois pgvecto.rs
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.rnids.rs

domain:       RS

organisation: Serbian National Internet Domain Registry (RNIDS)
address:      Zorza Klemansoa 18a
address:      Belgrade 11008
address:      Serbia

contact:      administrative
name:         RNIDS Admin Contact
organisation: Serbian National Internet Domain Registry (RNIDS)
address:      Zorza Klemansoa 18a
address:      Belgrade 11008
address:      Serbia
phone:        +381 11 7281281
fax-no:       +381 11 7281282
e-mail:       tld-admin@rnids.rs

contact:      technical
name:         RNIDS Tech Contact
organisation: Serbian National Internet Domain Registry (RNIDS)
address:      Zorza Klemansoa 18a
address:      Belgrade 11008
address:      Serbia
phone:        +381 11 7281281
fax-no:       +381 11 7281282
e-mail:       tld-tech@rnids.rs

nserver:      A.NIC.RS 2001:67c:69c:0:0:0:0:59 91.199.17.59
nserver:      B.NIC.RS 195.178.32.2 2a00:e90:0:3:0:0:0:3
nserver:      F.NIC.RS 2001:500:14:6032:ad:0:0:1 204.61.216.32
nserver:      G.NIC.RS 147.91.8.6
nserver:      H.NIC.RS 2001:67c:69c:0:0:0:0:60 91.199.17.60
nserver:      L.NIC.RS 194.146.106.114 2001:67c:1010:29:0:0:0:53
ds-rdata:     57382 13 2 9aca8316c4ce272097297cf5700e8a66e00ad0c83c4165bfcc90659438dc1794

whois:        whois.rnids.rs

status:       ACTIVE
remarks:      Registration information: http://www.rnids.rs

created:      2007-09-24
changed:      2021-07-20
source:       IANA

# whois.rnids.rs

%ERROR:103: Domain is not registered%

no, I don't work for the domain company, but wouldn't it be a shame if some random blue jeans company buys it?

**Comment by VoVAllen** [comment]
Thanks for your suggestion! Actually I've checked GoDaddy and Namecheap but they all said rs domains are not available, so I thought it was not available at all. I'll check more domain providers!

**Comment by suyanhanx** [comment]
It seems that these two domain providers, [ISTanCo](https://www.istanco.rs/) and [gandi](https://www.gandi.net/en/domain/tld/rs), can buy rs domain on them.

**Comment by BeautyyuYanli** [comment]
Available on [ISTanCo](https://www.istanco.rs/) and [gandi](https://www.gandi.net/en/domain/tld/rs) now. @VoVAllen

**Comment by dataf3l** [comment]
![image](https://github.com/tensorchord/pgvecto.rs/assets/3528304/6e3d08e0-2bc5-4572-9346-7914f839329c)

**Comment by gaocegege** [comment]
We already bought the domain name! Thanks for the issue. We are working on the documentation website now.
