### ISSUE TITLE
Binary vectors and Index

### ISSUE THREAD

**Issue by AmineDiro** [tensorchord/pgvecto.rs#86]
Hello,

I want to first thank you for the excellent job you're doing in this extension ! `pgvector` is a perfect project but lacks in performance and extensibility areas and this project is really solving all these issues.

As an ML engineer, I usually need to store binary vectors (generated from perceptual hash for example). the current answer I found is to store the binary vector as an f32 vector of {0,1} representing the binary data. L2 distance is used as it mirrors the hamming distance. Unfortunately, this solution consumes unnecessary space and L2 distance computation on 256-dim floats is far more expensive than a xor+popcount of 256bit vec. 

Looking at the current code I see that the core type is a pub a `Scalar` which is a wrapper type around a `f32`. All computation assumes a `&[Scalar]`. How difficult would it be to support a `&[u8]` which maps to postgres `bytea` datatype. I would love to contribute to this feature if this is something worth working on 😃  !  Thanks

**Comment by VoVAllen** [comment]
Thank you for your interest and contributions are greatly appreciated. 

For the binary support, there're actually two part, how to store the binary vector inside postgres, and the implementation of binary vector search at the vector search part. And we can reuse the binary vector search part for the binary quantization, like qdrant's latest [blog](https://qdrant.tech/articles/binary-quantization/). 

I think we can start with the vector search part by supporting binary vector search first, and then try to store it efficiently in postgres. @usamoi can introduce more on the technical details

**Comment by AmineDiro** [comment]
Thanks @VoVAllen  for the response, you're correct I did miss the quantization part of distance computation. The `Distance` does implement `scalar_quantization_distance` and ` scalar_quantization_distance2` that takes two '`&[u8]`. The issue here is that I don't really think we can reuse those for computing the hamming distance between binary data if we don't have them stored as binary, or at least  I don't know how to do so. The issue here is that `hamming` should be a separate distance from L2 and should be added as a variant to `Distance`.
```rust
pub enum Distance {
    L2,
    Cosine,
    Dot,
   Hamming,
}
```
But the impl distance is tightly coupled with the `Scalar` struct. For hamming distance, you shouldn't have to operate on the `Scalar` data. Maybe having a generic `T : Data` where `Data` ressembles [RawData](https://docs.rs/ndarray/latest/ndarray/trait.RawData.html) trait 🤔 could resolve this ?

**Comment by gaocegege** [comment]
@usamoi could you please help answer the question?

**Comment by usamoi** [comment]
Binary vectors require a lot of work. Maybe we should implement binary quantization. It is simpler and saves memory too.

**Comment by usamoi** [comment]
Completed in #368

**Comment by gaocegege** [comment]
Here is an example:

```
CREATE TABLE items (
  id bigserial PRIMARY KEY,
  embedding bvector(3) NOT NULL
);

INSERT INTO items (embedding) VALUES ('[1,0,1]'), ('[0,1,0]');
```

**Comment by gaocegege** [comment]
We wrote a post for the feature: https://blog.pgvecto.rs/my-binary-vector-search-is-better-than-your-fp32-vectors
