### ISSUE TITLE
blog: Introduce filter support in pgvecto.rs versus pgvector

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs#94]
Introduce how we solve the filter/dead tuple problem in pgvector, by a prefilter/postfilter that can be manually controlled by the user

Reference:
pgvector exsiting issue: 
- https://github.com/pgvector/pgvector/issues/301
- https://github.com/pgvector/pgvector/issues/259
- https://github.com/pgvector/pgvector/issues/244

**Comment by usamoi** [comment]
tracking in https://github.com/tensorchord/pgvecto.rs/issues/244
