### ISSUE TITLE
feat: Build Docker Image for Windows and macOS

### ISSUE THREAD

**Issue by BeautyyuYanli** [tensorchord/pgvecto.rs#99]
relate to:
- #56 
- [ac38d3f](https://github.com/tensorchord/pgvecto.rs/pull/95/commits/ac38d3ffa6b1fcc4ba9934ac0fdd33ee1ef289d0) && https://github.com/tensorchord/pgvecto.rs/actions/runs/6617214540/job/17973080897?pr=95

**Comment by kemingy** [comment]
I don't think it works on Windows due to the Unix Domain Socket.

**Comment by BeautyyuYanli** [comment]
> I don't think it works on Windows due to the Unix Domain Socket.

seems Postgres can run on Windows ?

**Comment by kemingy** [comment]
> > I don't think it works on Windows due to the Unix Domain Socket.
> 
> seems Postgres can run on Windows ?

It's used by pgvecto.rs for IPC. Ref https://github.com/tensorchord/pgvecto.rs/pull/88

**Comment by BeautyyuYanli** [comment]
1. Any method to test the clients (i.e. Python binding) in Windows and macOS? Provide a remote pg server to connect?
2. I thought many AI developers use Windows or macOS. It's useful for them to try pgvecto.rs locally.

**Comment by workingjubilee** [comment]
PGRX doesn't fully support Windows, see:
- https://github.com/pgcentralfoundation/pgrx/issues/1137
- https://github.com/pgcentralfoundation/pgrx/issues/1133
- https://github.com/pgcentralfoundation/pgrx/issues/1132
- https://github.com/pgcentralfoundation/pgrx/issues/1129

On the other hand, it's slowly getting better:
- https://github.com/pgcentralfoundation/pgrx/pull/1367

**Comment by gaocegege** [comment]
The image works well in Windows WSL. I will test if it works on macOS M1.

**Comment by gaocegege** [comment]
I've tested on macOS, it works well. Closing this issue.
